### ISSUE TITLE
How can I start dr_agent?!

### ISSUE THREAD

**Issue by hamakh11** [FoundationDB/fdb-kubernetes-operator#1010]
I have installed the latest version of foundation DB on RHEL 8 and I want to use the **fdbdr** tool.
but the problem is when I start the fdbdr tool I get: **no running dr_agent found.**
I don’t know how to start the dr_agent and there is nothing shown in the official documentation about how to start or get the binaries for that daemon.

Thanks,

**Comment by johscheuer** [comment]
Are you running FoundationDB on Kubernetes with the operator or somewhere else e.g. VMs with your own install mechanism? The binaries are included in the official packages: https://www.foundationdb.org/download + https://apple.github.io/foundationdb/backups.html#dr-agent-command-line-tool.

If you are running FDB on Kubernetes with the operator a DR setup is currently not supported with the operator you have to create two clusters and create/configure the `dr_agent` by yourself.

**Comment by hamakh11** [comment]
Am running it on a VM with RHEL 8, I tried to awake the dr_agent as the documentation says with:
 
**dr_agent [-h] [-v] -d <CLUSTER_FILE> -s <CLUSTER_FILE>**

but I got no response from the command, it will standstill with no output.
also when I try to run:
 
**fdbdr status** 

I get this: 

Trace: addr2line -e fdbdr.debug -p -C -f -i 0xa9a655 0x7f2d5617bb20 0x65835b 0x65c214 0x4f9998 0x5eeaef 0x917698 0x8494c8 0x84976f 0x846868 0x846b3d 0x84b4e0 0x8c22b8 0x87b7fc 0x87b90f 0x868ac8 0x866a18 0x866bcd 0x880d58 0x7d3228 0x7ec27b 0x9fd40b 0x9fd505 0x4f9900 0xaf5840 0x841712 0x4b3573 0x7f2d5583d493
Segmentation fault (core dumped)

**Comment by johscheuer** [comment]
This repository is about FoundationDB on Kubernetes with the operator, so your question is better suited in the forum https://forums.foundationdb.org. I assume you actually replaced the placeholder `<CLUSTER_FILE>` with the destination and source cluster.

You should check in `/var/log/fdb/` for the log messages, those should have more information.

Closing this one and move the conversation into the forum.
