### ISSUE TITLE
FDB Operator on EKS [Docs]

### ISSUE THREAD

**Issue by innerop** [FoundationDB/fdb-kubernetes-operator#102]
Hi,

Is there any chance of documenting how to deploy FDB on AWS EKS using this FDB operator?

I’d like to adopt FDB and promote its adoption with others who are building real-time transactional systems and could use the causal consistency guarantee in a distributed db that can be deployed and managed via a service like EKS.

It would be fantastic to have a detailed guide in the docs.

🙏

**Comment by brownleej** [comment]
I think an EKS example could be super helpful, but I don't have any experience with EKS, so I'm not sure what we would want to customize for that kind of environment.

**Comment by johscheuer** [comment]
@innerop did you have any time to run the operator on an EKS cluster? I wouldn't expect that there is anything to change since the operator doesn't do any special things. The operator should work out of the box on all Kubernetes clusters with the version `1.15.0+`.

**Comment by innerop** [comment]
Good to know! We went with an on-prem solution. The cost of using AWS and EKS for that particular application didn't make a lot sense financially. Thanks for the follow up.
