### ISSUE TITLE
Better documentation and processes for release process

### ISSUE THREAD

**Issue by johscheuer** [FoundationDB/fdb-kubernetes-operator#1050]
We should document the steps for a release and add some scripts to do most of the work (with some additional checks). I think most of the required steps are pretty simple (since most of the work is done in the GitHub action). We probably want to have at least the following tools:

- A tool to create the changelog automatically (e.g. with use of https://docs.github.com/en/rest/reference/pulls), this might also require some changes to the pr template.
- A tool to update the tag in our deployment files + helm files.
- A tool that checks if all prerequisites are in place (changelog, tag updates).

If I'm missing something please add a comment with the missing step.

PS.: By tool I mean either a small script or a small program whatever does the job and is sustainable :) 

CC @brownleej , @JoshuaMcManus and @ltsampros

**Comment by johscheuer** [comment]
I added this one as part of: https://github.com/FoundationDB/fdb-kubernetes-operator/pull/1049 to ensure our release process doesn't miss any steps the next time and requires less manual steps.

**Comment by ammolitor** [comment]
https://github.com/FoundationDB/fdb-kubernetes-operator/commit/0685a836efcf547250dcba8c75ac65e29ae9ea26

**Comment by johscheuer** [comment]
Closing this one, thanks!
