### ISSUE TITLE
make container-build fails to build image on Apple M1

### ISSUE THREAD

**Issue by ovaistariq** [FoundationDB/fdb-kubernetes-operator#1065]
### What happened?

`make container-build` fails with the following error:

```
 => ERROR [builder  2/23] RUN set -eux &&  curl --fail -L ${FDB_WEBSITE}/${FDB_VERSION}/foundationdb-clients_${FDB_VERSION}-1_amd64.deb -o fdb.deb &&  dpkg -i fdb.deb && rm fdb.deb &&  mkdir -p /usr/bin/fdb/${FDB_VERSION%.*} &&  fo  2.7s
------
 > [builder  2/23] RUN set -eux &&      curl --fail -L ${FDB_WEBSITE}/${FDB_VERSION}/foundationdb-clients_${FDB_VERSION}-1_amd64.deb -o fdb.deb &&      dpkg -i fdb.deb && rm fdb.deb &&        mkdir -p /usr/bin/fdb/${FDB_VERSION%.*} &&   for binary in fdbbackup fdbcli; do               download_path=/usr/bin/fdb/${FDB_VERSION%.*}/$binary &&                 curl --fail -L ${FDB_WEBSITE}/${FDB_VERSION}/$binary.x86_64 -o $download_path &&                chmod u+x $download_path;     done &&         mkdir -p /usr/lib/fdb:
#12 1.072 + curl --fail -L https://github.com/apple/foundationdb/releases/download/6.2.30/foundationdb-clients_6.2.30-1_amd64.deb -o fdb.deb
#12 1.124   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
#12 1.124                                  Dload  Upload   Total   Spent    Left  Speed
100   678  100   678    0     0   2690      0 --:--:-- --:--:-- --:--:--  2690
100 13.3M  100 13.3M    0     0  14.7M      0 --:--:-- --:--:-- --:--:-- 14.7M
#12 2.035 + dpkg -i fdb.deb
#12 2.209 dpkg: error processing archive fdb.deb (--install):
#12 2.209  package architecture (amd64) does not match system (arm64)
#12 2.326 Errors were encountered while processing:
#12 2.326  fdb.deb
------
executor failed running [/bin/sh -c set -eux && 	curl --fail -L ${FDB_WEBSITE}/${FDB_VERSION}/foundationdb-clients_${FDB_VERSION}-1_amd64.deb -o fdb.deb && 	dpkg -i fdb.deb && rm fdb.deb && 	mkdir -p /usr/bin/fdb/${FDB_VERSION%.*} && 	for binary in fdbbackup fdbcli; do 		download_path=/usr/bin/fdb/${FDB_VERSION%.*}/$binary && 		curl --fail -L ${FDB_WEBSITE}/${FDB_VERSION}/$binary.x86_64 -o $download_path && 		chmod u+x $download_path; 	done && 	mkdir -p /usr/lib/fdb]: exit code: 1
make: *** [container-build] Error 1
```

As the error message says this is due to the difference in package and system architecture.

### What did you expect to happen?

Build to be successful.

### How can we reproduce it (as minimally and precisely as possible)?

By running `make container-build`

### Anything else we need to know?

Docker supports cross-platform builds. So appending `--platform linux/amd64` to the build command fixes the issue.

Is there a reason why the platform should not be set to amd64?

### FDB Kubernetes operator

Operator isn't installed yet. I am testing it in my local environment.

### Kubernetes version

Operator isn't installed yet. I am testing it in my local environment.

### Cloud provider

Local environment on Apple M1 Macbook

**Comment by johscheuer** [comment]
I think it's a good idea to add `--platform linux/amd64` per default. We probably want to have something that can be overwritten if required e.g. `BUILDER_ARGS` (similar to: https://github.com/FoundationDB/fdb-kubernetes-operator/blob/main/Makefile#L34), per default this variable could hold the value `--platform linux/amd64` but also allow users to overwrite it if they want/need.

Please feel free to make the required changes in the Makefile and open a PR to merge those changes.

**Comment by ovaistariq** [comment]
I have created PR #1072. I have retained the default behavior so by default we don't change the build platform.

**Comment by johscheuer** [comment]
Thanks for your PR. I would close this PR since building on Apple M1 is now supported with your changes. If there is anything else either reopen the issue or open a new one.
