### ISSUE TITLE
Add watch-namespace flag to deployment again

### ISSUE THREAD

**Issue by johscheuer** [FoundationDB/fdb-kubernetes-operator#1095]
### What would you like to be added/changed?

Once we have a new release of the operator we should add the `--watch-namespace` flag again in our sample deployments:

```yaml
       args:
        - "-watch-namespace"
        - "$(WATCH_NAMESPACE)"
```

**Comment by brownleej** [comment]
Is the intent of having this flag in the samples for documentation purposes, or for functional purposes?

**Comment by johscheuer** [comment]
The intent was to have the same state like before. Since the flag is already documented we can also decide to just use the default (which is the value of the env variable).
