### ISSUE TITLE
Avoiding a two-step creation of the config map when using DNS names

### ISSUE THREAD

**Issue by brownleej** [FoundationDB/fdb-kubernetes-operator#1109]
### What would you like to be added/changed?

When we are first creating a cluster, we currently create the config map with a placeholder cluster file, then create the pods, and then update the cluster file with the initial coordinators. This slows down the cluster creation, because we have to wait for the cluster file to propagate. When using DNS names in the cluster file, we may be able to choose the initial coordinators before creating the pods, because the DNS names will be predictable. We should try this to see if we can create the cluster without having to update the config map a second time, and ideally with only a single pass through the reconciliation loop.

**Comment by johscheuer** [comment]
The problem with creating the initial connection without waiting for enough pods to be up and running is that the operator doesn't know where the pods will be running. So the usefulness of this approach would be limited to cases where the fault domain will be the pod itself. Given the limited cases where we could make use of that (only for the pod fault domain and only during the initial creation) I would close this issue and tend to not implement this.
