### ISSUE TITLE
allowTagOverride not implemented in 1.2 or above  in the operator

### ISSUE THREAD

**Issue by TSTTang** [FoundationDB/fdb-kubernetes-operator#1173]
### What happened?

In 0.34 or above operator code, we can set the allowTagOverride to override the use of version for the image tag.  But in 1.2 and 1.3 operator, this feature is broken.

### What did you expect to happen?

allowTagOverride should work.

### How can we reproduce it (as minimally and precisely as possible)?

In a cluster yaml, set the image tag in the image line and set allowTagOverride to true.
The cluster should be provision without any issue.

### Anything else we need to know?

In the pod_models.go, in 0.48.0 version, at GetImage function:
func GetImage(image string, configs []fdbtypes.ImageConfig, versionString string, allowOverride bool) (string, error) {
        if image != "" {
                imageComponents := strings.Split(image, ":")
                if len(imageComponents) > 1 {
                        if !allowOverride {
                                // If the specified image contains a tag and allowOverride is false return an error
                                return "", fmt.Errorf("image should not contain a tag but contains the tag \"%s\", please remove the tag", imageComponents[1])
                        }
                        return image, nil
                }
                configs = append([]fdbtypes.ImageConfig{{BaseImage: image}}, configs...)
        }

        return fdbtypes.SelectImageConfig(configs, versionString).Image(), nil
}
It has the allowOverride checking, but in master and 1.2, I don't see that in the function:
// GetImage returns the image for container
func GetImage(image string, configs []fdbv1beta2.ImageConfig, versionString string) (string, error) {
        if image != "" {
                imageComponents := strings.Split(image, ":")
                if len(imageComponents) > 1 {
                        // If the specified image contains a tag and allowOverride is false return an error
                        return "", fmt.Errorf("image should not contain a tag but contains the tag \"%s\", please remove the tag", imageComponents[1])
                }
                configs = append([]fdbv1beta2.ImageConfig{{BaseImage: image}}, configs...)
        }

        return fdbv1beta2.SelectImageConfig(configs, versionString).Image(), nil
}

and when try to provision a cluster with tag override, it won't work with the 1.2 operator

### FDB Kubernetes operator

<details>
```console
$ kubectl fdb version
kubectl fdb version
foundationdb-operator: 1.2

```

</details>

### Kubernetes version

<details>

```console
$ kubectl version
kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v0.21.0-beta.1", GitCommit:"96e95cef877ba04872b88e4e2597eabb0174d182", GitTreeState:"clean", BuildDate:"2021-09-10T10:44:50Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.3+e419edf", GitCommit:"6f5a5295923a614a4202a7ad274b38b69f9ca8c0", GitTreeState:"clean", BuildDate:"2022-02-25T06:26:46Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (0.21) and server (1.23) exceeds the supported minor version skew of +/-1
```

</details>

### Cloud provider

<details>

</details>

**Comment by thorn126** [comment]
@TSTTang It is deprecated , https://github.com/FoundationDB/fdb-kubernetes-operator/pull/981
