### ISSUE TITLE
Upgrading Minio in operator testing environment

### ISSUE THREAD

**Issue by brownleej** [FoundationDB/fdb-kubernetes-operator#1174]
### What would you like to be added/changed?

We have a deployment of the Minio operator in our development environment, running version 1.0.7 of the Minio operator. The latest version of this operator is 4.4.16. I've hit issues installing version 1.0.7 in a fresh environment, due to the configuration using a v1beta1 resource that newer versions of Kubernetes don't accept. I think we should update to the latest version of the Minio operator.

**Comment by johscheuer** [comment]
Since Minio changed their licensing we probably want to drop Minio and see if we can find a replacement for it.
