### ISSUE TITLE
Race condition when recreating a pod during an upgrade

### ISSUE THREAD

**Issue by brownleej** [FoundationDB/fdb-kubernetes-operator#1178]
### What happened?

During an upgrade, we perform the following steps:

1. Update the image version for the sidecar container in each pod to inject new binaries
2. Bounce the fdbserver processes so they start running the new binaries
3. Update the running version in the resource status to reflect that the cluster is running the new version
4. Recreate the pods so the main container is running the new version

There can be a delay between steps 1 and 2, if one of the pods is failing to update. This is more likely in a multi-DC configuration, because we need the pods to be updated in all of the DCs. If a pod gets deleted between steps 1 and 2, the operator will recreate it with the init container and main container at the old version, and the sidecar container at the new version. The init container will generate a monitor conf referencing the binary in /usr/bin/fdbserver, which is the old version. Then in parallel we will start the main container and the sidecar container. The main container may load the monitor conf from the init container referencing the old version, or it may load the monitor conf from the sidecar referencing the new version, depending on the timing of the two container launches.

### What did you expect to happen?

The desired behavior here isn't obvious because it's ambiguous what the desired version for the binary is. At a minimum we should make it consistently produce a single version depending on the operator's understanding of the state of the cluster.

### How can we reproduce it (as minimally and precisely as possible)?

1. Start a multi-DC cluster on FDB 6.3
2. Start an upgrade in DC1 to FDB 7.1, and leave the others on 6.3
3. Delete all the pods in DC1
4. Observe the distribution of fdbserver versions that are running in the pods.

### FDB Kubernetes operator

<details>

1.3.0

</details>

### Kubernetes version

<details>

v1.19.13
</details>

### Cloud provider

<details>
N/A
</details>

**Comment by johscheuer** [comment]
I would expect that if a Pod get's deleted between step 1-2 that the operator is able to converge the state of this Pod to the new version again. We should always try. to reconcile the state based on the version defined in the cluster spec.

**Comment by brownleej** [comment]
> We should always try. to reconcile the state based on the version defined in the cluster spec.
Are you suggesting that we should run all of the containers at the version defined in the cluster spec when creating a new pod? That creates a possibility that the rest of the cluster hasn't been upgraded to the new version, leaving the process in that new pod unable to communicate with the database. It's also harder to walk back from that, because once the fdbserver process launches on the new version it may make changes to the data directory that render it unusable on the old version. However, that may be the risk we need to take, and its similar to what would happen if the fdbserver or fdbmonitor process terminated for some other reason between steps 1 and 2.

**Comment by johscheuer** [comment]
We discussed this offline and decided that the best approach is to move forward with stabilizing the unified image approach.
