### ISSUE TITLE
Misleading documentation about caching for getFDBDatabase

### ISSUE THREAD

**Issue by brownleej** [FoundationDB/fdb-kubernetes-operator#1212]
### What would you like to be added/changed?

In the documentation for `getFDBDatabase` in `fdbclient`, it says "The result will be cached for subsequent calls". This is no longer accurate, because we have removed the caching behavior. I think we should update the documentation to reflect the current behavior.

**Comment by johscheuer** [comment]
Closing this one as the statement is not there anymore.
