### ISSUE TITLE
Improve update logic to update/replace coordinators after everything else is upgraded

### ISSUE THREAD

**Issue by johscheuer** [FoundationDB/fdb-kubernetes-operator#1218]
### What would you like to be added/changed?

This has the benefit that an upgrade should be faster since the number of coordinator changes will be reduced. Currently we randomly update Pods this means that in the worst case we update one Pod after another which was a coordinator. Every coordinator update will delay the upgrade since the coordinator change will be coordinated between the different operators for HA clusters and we have to do some additional work on the operator side.

**Comment by johscheuer** [comment]
We should run some "benchmarks" for the current behaviour and for the new behaviour to see how significant the benefit is.

**Comment by brownleej** [comment]
Is this the kind of update described here a rolling bounce? I think we have a path to eliminate the coordinator changes in that flow, once we can use DNS names for the coordinators.

**Comment by johscheuer** [comment]
That's correct, i referring here to the rolling bounce of the SS Pods and the upgrade refers o any changes that require a rolling upgrade, not only the rolling bounce after a version upgrade. I don't think that the DNS support will be a huge help here, since the coordinator still will bee unavailable for period of time and depending on the race condition thee operator will decide to choose a new coordinator since the old one is not available.

**Comment by johscheuer** [comment]
I verified that a coordinator change won't trigger a recovery. So the value of this won't be too big.
