### ISSUE TITLE
Reconciliation getting stuck when moving the cluster from DNS names to IPs

### ISSUE THREAD

**Issue by brownleej** [FoundationDB/fdb-kubernetes-operator#1226]
### What happened?

During a test of enabling and disabling the feature to use DNS names in the cluster file, reconciliation got stuck. It was reconfiguring the pod specs to remove the DNS configuration, which caused the operator to replace the transaction subsystem. The replacement pods came up with a cluster file that used DNS names, but the processes weren't able to connect because the DNS names were no longer usable.

### What did you expect to happen?

I would expect the DNS names to remain resolvable until after the other changes to the cluster were completed.

### How can we reproduce it (as minimally and precisely as possible)?

I think we can reproduce this by turning DNS names on and off using the latest FDB build, but there may be race conditions involved.

### FDB Kubernetes operator

<details>

```console
$ kubectl fdb version
# paste output here
```

</details>

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

<details>

</details>

**Comment by johscheuer** [comment]
Like I mentioned in the related PR: https://github.com/FoundationDB/fdb-kubernetes-operator/pull/1228#discussion_r875534254 I think we can use a simple check to see if the connection string uses hostnames.
