### ISSUE TITLE
Communication channel for development

### ISSUE THREAD

**Issue by psalaberria002** [FoundationDB/fdb-kubernetes-operator#125]
We are looking into running the FoundationDB at scale in +10 Kubernetes clusters. The operator is most probably our best option here. Really excited about this project!

As this operator is in early stages, we will need to contribute, and we are happy to do so.

What's the preferred communication channel for development related questions/discussions? Do you have a Slack channel? It's hard to do this solely based on Github issues.

Thanks!

**Comment by brownleej** [comment]
I think that in general we want to share communication channels with the main FoundationDB project. We don't have a public slack at this time, but it's something we're considering for the future. In the mean time, we can use the [FoundationDB forums](forums.foundationdb.org) as a discussion channel. We may create a dedicated space in there for the Kubernetes operator, but for now the "Development" and "Using FoundationDB" channels should be fine to use for this project.

**Comment by psalaberria002** [comment]
Thank you for the fast reply. Sharing the communication channels with the FoundationDB project makes total sense. A Slack workspace for the project, and a channel for the operator would be ideal.

Could you talk to the people who can set this up? We will use the forums meanwhile, but in order to contribute we will need a faster channel. 

Thanks again.

**Comment by brownleej** [comment]
I've created a new category in the forums for [Developing the Operator](https://forums.foundationdb.org/c/development/kubernetes-operator-development/15), as well as a new category for [Using the Operator](https://forums.foundationdb.org/c/using-foundationdb/kubernetes-operator/16). In terms of having an alternate channel for discussions like Slack, I think we should move that discussion to the forums to make sure we can get input from more folks who would be interested in that.
