### ISSUE TITLE
Restart processes wth DiskError or IOError

### ISSUE THREAD

**Issue by johscheuer** [FoundationDB/fdb-kubernetes-operator#1274]
### What would you like to be added/changed?

We should allow the operator to restart processes that contain an error message for a given period e.g. 12h. Initially we should focus on `io_error` and `io_timeout` those issues can happen if the underlying disk returns an error or is slow responding. If a process sees such an error it normally restarts and keeps the error message until It is restarted. In addition to that the process will keep the old sqlite file for further debugging, which can take up a significant amount of disk space. Letting the operator automatically restart a process after 12h (should be configurable) allows the cluster to recover the disk space again if the process only saw an intermediate issue.

```text
  "messages":[
            {
               "time":12345.12312,
               "type":"x",
               "name":{ // when not limiting
                  "$enum":[
                     "file_open_error",
                     "incorrect_cluster_file_contents",
                     "trace_log_file_write_error",
                     "trace_log_could_not_create_file",
                     "trace_log_writer_thread_unresponsive",
                     "process_error",
                     "io_error",
                     "io_timeout",
                     "platform_error",
                     "storage_server_lagging",
                     "(other FDB error messages)"
                  ]
               },
               "raw_log_message":"<stuff/>",
               "description":"abc"
            }
         ],
```

Documentation for the json format: https://apple.github.io/foundationdb/mr-status.html

**Comment by johscheuer** [comment]
Adding `StorageServerFailed` to the list.

**Comment by xumengpanda** [comment]
If we below we should automatically restart this, we can do this in FDB to let the process recruit another SS role automatically.

**Comment by johscheuer** [comment]
Closing this one, we don't plan to use this in the operator.
