### ISSUE TITLE
Error while installing the operator manifest

### ISSUE THREAD

**Issue by viveksinghggits** [FoundationDB/fdb-kubernetes-operator#128]
We get below error, if we just follow the step that is mentioned in the README to install the operator 

```
kubectl apply -f https://raw.githubusercontent.com/foundationdb/fdb-kubernetes-operator/master/config/samples/deployment.yaml -n fdb-err
Warning: kubectl apply should be used on resource created by either kubectl create --save-config or kubectl apply
role.rbac.authorization.k8s.io/fdb-kubernetes-operator-manager-role created
rolebinding.rbac.authorization.k8s.io/fdb-kubernetes-operator-manager-rolebinding created
deployment.apps/fdb-kubernetes-operator-controller-manager created
The CustomResourceDefinition "foundationdbclusters.apps.foundationdb.org" is invalid: metadata.annotations: Too long: must have at most 262144 characters
```

It seems the resource manifest is too long.

**Comment by brownleej** [comment]
Ah, you're right. I think the addition of the pod spec to the CRD caused it to get too long for `kubectl apply` to handle. There's a similar issue on the kubebuilder repo: https://github.com/kubernetes-sigs/kubebuilder/issues/1140

**Comment by viveksinghggits** [comment]
@brownleej there seems to be another issue, if I just `kubectl apply` the manifests that are mentioned in the README, we get the error in the operator pod saying its not able to list the pods. I think you might wanna look at that as well.

**Comment by brownleej** [comment]
Can you clarify which manifests you are installing? I would expect the deployment.yaml to hit the issue you described above with the annotation length. Absent that manifest, you wouldn't have the operator installed at all, unless you installed it through some other means, which could cause the permissions issue you're seeing.

**Comment by viveksinghggits** [comment]
I will post the details in some time.

**Comment by brownleej** [comment]
I've made a change to remove the CRD from the sample deployment, and updated the README with new installation instructions. @viveksinghggits Can you see if you are able to install the operator based on the updated instructions?
