### ISSUE TITLE
Kubectl plugin for fdb operations

### ISSUE THREAD

**Issue by akshaychitneni** [FoundationDB/fdb-kubernetes-operator#131]
Following https://kubernetes.io/docs/tasks/extend-kubectl/kubectl-plugins/, we can extend the kubectl to support easy operations with fdb-operator,

To start with, it can be kubectl fdb scale sample-cluster <process-type> 3 or simple get operation for logs/metrics per process

**Comment by brownleej** [comment]
Yeah, that sounds great!

**Comment by johscheuer** [comment]
I close this issue since we got a simple plugin and some additional issues to extend the plugin. Feel free to open an issue for your use case if you can't find it. Thanks for reporting!
