### ISSUE TITLE
Allow fix-coordinator-ips to fix IPs even if IPs are missing for ProcessGroups

### ISSUE THREAD

**Issue by johscheuer** [FoundationDB/fdb-kubernetes-operator#1351]
### What would you like to be added/changed?

We could initially try to get the new connection string by iterating over the `ProcessGroups` and if that's possible proceed with the correction mechanism. If that's not possible we have to exec into all Pods and check if the data directory contains a file like `coordination-*.fdq`, if so this process is a coordinator. We can skip all Pods that are not eligible for the coordinator role.

**Comment by brownleej** [comment]
We should make sure we don't get false positives from processes that used to be coordinators, but aren't anymore.
