### ISSUE TITLE
updates to cluster.spec.RunningVersion

### ISSUE THREAD

**Issue by akshaychitneni** [FoundationDB/fdb-kubernetes-operator#136]
Shouldnt the RunningVersion be defined in the cluster.Status object where the user cannot update? 

Right now the RunningVersion is defined in the spec and the user can update it. Although this triggers the reconciliation, it resets back to the Version in the spec. I think the additional reconciliation can be avoided moving RunningVersion to Status subresource.

**Comment by brownleej** [comment]
I think the running version is in awkward place between spec and status, based on how they are described in the [API Conventions](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#spec-and-status). The running version is not quite describing the "desired state", but it is used to generate pod specs. It also cannot be easily determined if it were lost, which the conventions say is necessary when something is stored in the status. In general the RunningVersion will match the Version, but they drift during the upgrade process, and we need to reliably track whether the processes are running at the new version both to determine certain aspects of the configuration (like what version to bring up newly added processes at) and to determine which version of the CLI we need to use to run commands against the cluster. I think it would be better eventually to get it into the status instead, but I think it would require having multi-version support in the CLI, or some other way that we could reliably fetch the running version dynamically.

**Comment by brownleej** [comment]
I should also add that there is no reason for someone to explicitly set the RunningVersion, other than maybe trying to work around bugs in the operator. and it is dangerous to set it explicitly. We should add documentation clarifying that, but it's also a good sign that it's not a good fit for the spec.

**Comment by akshaychitneni** [comment]
Thank you for your explanation. If we want to use RunningVersion, do you think it is better to fetch it from the cluster during the reconciliation?

**Comment by brownleej** [comment]
How would we fetch it from the cluster?

**Comment by akshaychitneni** [comment]
thought we can get the version from status call using the admin client.

**Comment by brownleej** [comment]
That relies on running the CLI, and we need the running version to know which version of the CLI to run.

**Comment by brownleej** [comment]
I've thought about this more, and I think there's a way we can store the running version, and other fields like that, in the status. We can use the config map as a fallback, and fetch the values from the config map if they're missing in the status. The config map is under the operator's control, and should be expected to managed by the operator rather than by the user. This should get us much closer to a point where we have a clean line between fields the user should be setting and fields the operator code should be setting.
