### ISSUE TITLE
Support multiple logs per pod

### ISSUE THREAD

**Issue by logo306142054** [FoundationDB/fdb-kubernetes-operator#1370]
### What would you like to be added/changed?

We can change the number of storage server per pod with the storageServersPerPod setting. This allows more efficient use of IOPS, since FDB is limited to a single core.
I think this is same to log process, so will we support to provision FDB with multiple logs on a single disk?

**Comment by xumengpanda** [comment]
This is an interesting idea. 
Have you benchmarked its impact on FDB's performance? Having two tLogs competing the same disk's IOPS might affect performance. 

tLog's disk capacity is typically over provisioned to keep the cluster available for hours when there are incidents in its downstream (i.e., storage servers). For the same size disk, sharing tLogs on a single disk will shorten the time we have to fix the downstream incidents without impacting cluster's availability. For high-density disk, it might be a good idea, assuming tLog's peak IOPS usage is less than 50% of disk's IOPS capacity.

**Comment by johscheuer** [comment]
I think most of the code should be in place to support this and the required changes should be fairly small. If you identify a need for this feel free to open a PR with the required changes and tests.
