### ISSUE TITLE
Encounter error message "unable to move FDB binaries"

### ISSUE THREAD

**Issue by liyyue** [FoundationDB/fdb-kubernetes-operator#1420]
### What happened?

Today I have deploy apple fdb operation 1.4.1 version from https://github.com/FoundationDB/fdb-kubernetes-operator and I use the dockerfile here https://github.com/FoundationDB/fdb-kubernetes-operator/blob/v1.4.1/Dockerfile ,
after deploy I found the following error message:
...
"level":"error","ts":1666935796.9896064,"logger":"setup","msg":"unable to move FDB binaries","error":"open /usr/bin/fdb: no such file or directory","stacktrace":"main.main\n\t/workspace/main.go:60\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:255"
...

Then I checked the dockerfile and found that there is no script to create the folder /usr/bin/fdb, but there are script to reference it:
...
ENV FDB_BINARY_DIR=/usr/bin/fdb
ENV FDB_NETWORK_OPTION_EXTERNAL_CLIENT_DIRECTORY=/usr/bin/fdb
...
Is there any bug for the dockerfile?

### What did you expect to happen?

I hope the operator can run without error

### How can we reproduce it (as minimally and precisely as possible)?

Just deploy the operator with the dockerfile in the repo

### FDB Kubernetes operator

<details>

```console
$ kubectl fdb version
# paste output here
```

</details>

1.4.1 version

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

<details>

</details>

**Comment by johscheuer** [comment]
Can you please provide some more information like the Deployment configuration of the operator?

**Comment by johscheuer** [comment]
In general the operator expects that the binaries are provided from the outside by init containers: https://github.com/FoundationDB/fdb-kubernetes-operator/blob/main/config/deployment/manager.yaml#L112-L113

**Comment by liyyue** [comment]
The following is the deployment yaml file:
...
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fdb-kubernetes-operator-controller-manager
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: fdb-kubernetes-operator-manager-role
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - configmaps
  - persistentvolumeclaims
  - events
  - secrets
  - services
  verbs:
  - get
  - watch
  - list
  - create
  - update
  - patch
  - delete
- apiGroups:
  - apps.foundationdb.org
  resources:
  - foundationdbclusters
  - foundationdbbackups
  - foundationdbrestores
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - update
  - patch
  - delete
- apiGroups:
  - apps.foundationdb.org
  resources:
  - foundationdbclusters
  - foundationdbbackups
  - foundationdbrestores
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - apps.foundationdb.org
  resources:
  - foundationdbclusters/status
  - foundationdbbackups/status
  - foundationdbrestores/status
  verbs:
  - get
  - update
  - patch
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - mutatingwebhookconfigurations
  - validatingwebhookconfigurations
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: fdb-kubernetes-operator-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: fdb-kubernetes-operator-manager-role
subjects:
- kind: ServiceAccount
  name: fdb-kubernetes-operator-controller-manager
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: fdb-kubernetes-operator-controller-manager
    control-plane: controller-manager
  name: fdb-kubernetes-operator-controller-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fdb-kubernetes-operator-controller-manager
  template:
    metadata:
      labels:
        app: fdb-kubernetes-operator-controller-manager
        control-plane: controller-manager
    spec:
      containers:
      - command:
        - /manager
        env:
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: FDB_TLS_CERTIFICATE_FILE
          value: /tmp/fdb-certs/tls.crt
        - name: FDB_TLS_CA_FILE
          value: /tmp/fdb-certs/ca.crt
        - name: FDB_TLS_KEY_FILE
          value: /tmp/fdb-certs/tls.key
        - name: DISABLE_SIDECAR_TLS_CHECK
          value: "1"
        #image: default-route-openshift-image-registry.apps.fdbtest2.cp.fyre.ibm.com/testoperator1/fdbopr:1.4.1
        image: image-registry.openshift-image-registry.svc:5000/testoperator1/fdbopr:1.4.1
        imagePullPolicy: Always
        name: manager
        ports:
        - containerPort: 8080
          name: metrics
        resources:
          limits:
            cpu: 500m
            memory: 256Mi
          requests:
            cpu: 500m
            memory: 256Mi
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          readOnlyRootFilesystem: true
        volumeMounts:
        - mountPath: /tmp
          name: tmp
        - mountPath: /var/log/fdb
          name: logs
        - mountPath: /var/fdb/data
          name: data
        - mountPath: /tmp/fdb-certs
          name: fdb-certs        
      initContainers:
      - args:
        - --copy-library
        - "6.2"
        - --copy-binary
        - fdbcli
        - --copy-binary
        - fdbbackup
        - --copy-binary
        - fdbrestore
        - --output-dir
        - /var/output-files/6.2.30
        - --init-mode
        image: foundationdb/foundationdb-kubernetes-sidecar:6.2.30-1
        name: foundationdb-kubernetes-init-6-2
        volumeMounts:
        - mountPath: /var/output-files
          name: fdb-binaries
      - args:
        - --copy-library
        - "6.3"
        - --copy-binary
        - fdbcli
        - --copy-binary
        - fdbbackup
        - --copy-binary
        - fdbrestore
        - --output-dir
        - /var/output-files/6.3.24
        - --init-mode
        image: foundationdb/foundationdb-kubernetes-sidecar:6.3.24-1
        name: foundationdb-kubernetes-init-6-3
        volumeMounts:
        - mountPath: /var/output-files
          name: fdb-binaries
      - args:
        - --copy-library
        - "7.1"
        - --copy-binary
        - fdbcli
        - --copy-binary
        - fdbbackup
        - --copy-binary
        - fdbrestore
        - --output-dir
        - /var/output-files/7.1.15
        - --init-mode
        image: foundationdb/foundationdb-kubernetes-sidecar:7.1.15-1
        name: foundationdb-kubernetes-init-7-1
        volumeMounts:
        - mountPath: /var/output-files
          name: fdb-binaries
      securityContext:
        #fsGroup: 4059
        #runAsGroup: 4059
        #runAsUser: 4059
      serviceAccountName: fdb-kubernetes-operator-controller-manager
      terminationGracePeriodSeconds: 10
      volumes:
      - emptyDir: {}
        name: tmp
      - emptyDir: {}
        name: logs
      - emptyDir: {}
        name: data
      - emptyDir: {}
        name: fdb-binaries  
      - name: fdb-certs
        secret:
          secretName:  internal-tls

**Comment by liyyue** [comment]
@johscheuer Thanks for your instruction! I have added the missed line in the deployment yaml file and the problem is fixed.
