### ISSUE TITLE
Implement Max Unavailable

### ISSUE THREAD

**Issue by johscheuer** [FoundationDB/fdb-kubernetes-operator#1444]
### What would you like to be added/changed?

We should implement a `Max Unavailable` setting similar to what a Kubernetes Deployment provides: https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#max-unavailable to prevent cases where the operator is deleting Pods and the new Pods are stuck in Pending. See https://github.com/FoundationDB/fdb-kubernetes-operator/pull/1236#discussion_r1032580981 for some more context.

**Comment by AdheipSingh** [comment]
@johscheuer id like to implement this one.

**Comment by johscheuer** [comment]
Sure, is there anything you need?
