### ISSUE TITLE
updateStatus is not idempotent, leading the operator to get stuck

### ISSUE THREAD

**Issue by sears** [FoundationDB/fdb-kubernetes-operator#1458]
### What happened?

I used a simulation environment to test cluster creation, and it found a few different hangs / failed cluster updates.

For example, reconciled process groups may be missing from the FDB cluster's kubernetes status, or an attempt to enable TLS may "succeed" even though TLS is apparently not enabled.

### What did you expect to happen?

Crashes immediately after updateStatus succeeds should not cause the operator / foundationdb to enter strange states.

### How can we reproduce it (as minimally and precisely as possible)?

Apply this patch (manually, the tabs cause all sorts of issues if you copy-paste):
```
diff --git a/controllers/cluster_controller.go b/controllers/cluster_controller.go
index 5b6d8325..7b57ac13 100644
--- a/controllers/cluster_controller.go
+++ b/controllers/cluster_controller.go
@@ -128,6 +128,7 @@ func (r *FoundationDBClusterReconciler) Reconcile(ctx context.Context, request c
 	}
 
 	subReconcilers := []clusterSubReconciler{
+		updateStatus{},
 		updateStatus{},
 		updateLockConfiguration{},
 		updateConfigMap{},
```
Then:
```
make test
```
The unit tests should pass (since it is always OK for the operator to be restarted between updateStatus and updateLockConfiguration, and this simulates that).  Instead, they fail.

### FDB Kubernetes operator

<details>
Using SHA: 2fdbadfa8f8e9dfaa281090150adbd2967473ed3
</details>

### Kubernetes version

<details>
N/A (though this also reproduces in Kind)
</details>

### Cloud provider

<details>
N/A
</details>

**Comment by sears** [comment]
I just rebased to main, and the above test failure minimization no longer works.  (I saw some issues regarding the handling of mock command line parameters, and that was recently fixed.)

I'm now trying to reproduce the original issue in the simulation environment.

**Comment by johscheuer** [comment]
Going to close this one as it seems the initial issue was with the mock client. Feel free to reopen it.
