### ISSUE TITLE
Create a ProcessGroupdID type with a maximum length

### ISSUE THREAD

**Issue by johscheuer** [FoundationDB/fdb-kubernetes-operator#1476]
### What would you like to be added/changed?

We have multiple places where we use a string instead of a dedicated type for parsing process group IDs. We should create a dedicated type for that with a maximum length limitation. Some of those references are used in the `BuggifyConfig` (see: https://github.com/FoundationDB/fdb-kubernetes-operator/blob/main/api/v1beta2/foundationdbcluster_types.go#L1691-L1708) but we should check the code in general to see where we should be using this new type.

**Comment by brownleej** [comment]
As another example, we recently added an `ignoreDuringRestart` field that contains process group IDs, which has no maximum string length.
