### ISSUE TITLE
IncorrectProcess message is logged using a global logger

### ISSUE THREAD

**Issue by brownleej** [FoundationDB/fdb-kubernetes-operator#1479]
### What happened?

In the `checkAndSetProcessStatus` function, there is an `IncorrectProcess` log event that is logged with a global logger. This means that it does not have log events with the cluster information, which are set on a local `logger` object in the function.

### What did you expect to happen?

I expected the log events to contain a `cluster` field.

### How can we reproduce it (as minimally and precisely as possible)?

Create a cluster, and then edit the process configuration to have custom parameters.

### FDB Kubernetes operator

latest, built off of main

### Kubernetes version

<details>

```console
ubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T21:16:14Z", GoVersion:"go1.16.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"22+", GitVersion:"v1.22.15-eks-fb459a0", GitCommit:"be82fa628e60d024275efaa239bfe53a9119c2d9", GitTreeState:"clean", BuildDate:"2022-10-24T20:33:23Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
EKS
</details>

**Comment by johscheuer** [comment]
@xumengpanda are you planning to work on this?
