### ISSUE TITLE
Better handling for node failures/taints

### ISSUE THREAD

**Issue by johscheuer** [FoundationDB/fdb-kubernetes-operator#1492]
### What would you like to be added/changed?

We should add optional support for detecting node failures and taints in the operator to proactively replace/move Pods away from such nodes.

**Comment by xumengpanda** [comment]
I'm going to use this issue as the meta-issue for all PRs related to taint feature.

**Comment by xumengpanda** [comment]
Feature PR: https://github.com/FoundationDB/fdb-kubernetes-operator/pull/1581

**Comment by xumengpanda** [comment]
Documentation PR: https://github.com/FoundationDB/fdb-kubernetes-operator/pull/1632
