### ISSUE TITLE
Upgrades stucks after sidecar crashes and recovered

### ISSUE THREAD

**Issue by vishesh** [FoundationDB/fdb-kubernetes-operator#1495]
### What happened?

- Crashloop a sidecar process
- Initiate ugprade
- Remove crashloop from sidecar process.
- All sidecar except crashed one gets upgraded.
- Main images are all not upgraded.

### What did you expect to happen?

Upgrades to continue and finish after sidecar process recovers.

### How can we reproduce it (as minimally and precisely as possible)?

https://github.com/FoundationDB/fdb-kubernetes-tests/pull/692

### FDB Kubernetes operator

449fb455f62d3872803d6f65d9eda51625c12dd7

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"22+", GitVersion:"v1.22.6-eks-7d68063", GitCommit:"f24e667e49fb137336f7b064dba897beed639bad", GitTreeState:"clean", BuildDate:"2022-02-23T19:32:14Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22+", GitVersion:"v1.22.16-eks-ffeb93d", GitCommit:"52e500d139bdef42fbc4540c357f0565c7867a81", GitTreeState:"clean", BuildDate:"2022-11-29T18:41:42Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}```

</details>


### Cloud provider

<details>

</details>

**Comment by johscheuer** [comment]
The issue was in the test case.
