### ISSUE TITLE
Making the cluster argument optional when we are removing pods in the remove process-groups command

### ISSUE THREAD

**Issue by brownleej** [FoundationDB/fdb-kubernetes-operator#1537]
### What would you like to be added/changed?

In the `kubectl-fdb remove process-groups` command, the default form takes a list of pod names. However, it also requires passing a cluster name through the `-c` argument. If we're specifying the pods, the command should be able to infer the cluster or clusters from the pod metadata, so making people specifying the cluster explicitly feels like unnecessary extra work. Can we remove that requirement?

**Comment by johscheuer** [comment]
That sounds like a great idea and @09harsh implement such a logic for the cordon command, we probably can reuse that logic.

**Comment by johscheuer** [comment]
We probably want to review all of our methods where we have to specify the Pod(s) and the cluster name and unify the handling here.
