### ISSUE TITLE
RBAC issues with listing PVC and pods

### ISSUE THREAD

**Issue by southwel** [FoundationDB/fdb-kubernetes-operator#156]
Following the guidance in the README on both an AKS and minikube, I see:

kubectl get pods
NAME                                                          READY   STATUS    RESTARTS   AGE
fdb-kubernetes-operator-controller-manager-7b79d48ccc-lg5f5   1/1     Running   0          8m23s

kubectl logs fdb-kubernetes-operator-controller-manager-7b79d48ccc-lg5f5 --container=manager

E0228 02:20:20.536336       1 reflector.go:156] pkg/mod/k8s.io/client-go@v0.17.0/tools/cache/reflector.go:108: Failed to list *v1.PersistentVolumeClaim: persistentvolumeclaims is forbidden: User "system:serviceaccount:default:default" cannot list resource "persistentvolumeclaims" in API group "" at the cluster scope
E0228 02:20:20.783869       1 reflector.go:156] pkg/mod/k8s.io/client-go@v0.17.0/tools/cache/reflector.go:108: Failed to list *v1.Pod: pods is forbidden: User "system:serviceaccount:default:default" cannot list resource "pods" in API group "" at the cluster scope

kubectl apply -f https://raw.githubusercontent.com/foundationdb/fdb-kubernetes-operator/master/config/samples/cluster_local.yaml

kubectl get foundationdbcluster sample-cluster
NAME             GENERATION   RECONCILED   HEALTHY
sample-cluster   1

All kubectl apply operations complete without error.

**Comment by southwel** [comment]
kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-13T18:06:54Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:07:13Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}

minikube version
minikube version: v1.7.3
commit: 436667c819c324e35d7e839f8116b968a2d0a3ff

**Comment by brownleej** [comment]
I think the problem here is that the default examples are using a RoleBinding to grant the permissions for these resources, which only grants them at the namespace level. It's trying to look for the resources at the cluster level instead. That's because the WATCH_NAMESPACE environment variable isn't being set. We should fix the example configurations to bring those two things in alignment.

**Comment by brownleej** [comment]
We should also add more documentation about these two modes because it may not be clear that this is a choice people have to make when running the operator.
