### ISSUE TITLE
Update variable pods to storagePod1 in update_status_tests

### ISSUE THREAD

**Issue by xumengpanda** [FoundationDB/fdb-kubernetes-operator#1600]
### What would you like to be added/changed?

variable [pods](https://github.com/FoundationDB/fdb-kubernetes-operator/blob/870cfeab5da97cf56f35ebee035ebaf3284bb304/controllers/update_status_test.go#L406) are actually storage-1 pod. It's quite confusing with the current variable name pods. Change it to storagePod1

**Comment by johscheuer** [comment]
Already changed.
