### ISSUE TITLE
Investigate the number of recoveries that happen during an HA cluster upgrade

### ISSUE THREAD

**Issue by sbodagala** [FoundationDB/fdb-kubernetes-operator#1607]
### What happened?

We have noticed that an HA cluster is going through about 30+ recoveries during upgrade (https://github.com/FoundationDB/fdb-kubernetes-operator/pull/1580), which is much higher than the anticipated number of recoveries (< 10). Investigate why the cluster is going through so many recoveries.

### What did you expect to happen?

The anticipated number of recoveries that the cluster should be going through is 8 (or, 8 + 1).

### How can we reproduce it (as minimally and precisely as possible)?

Details of the test are in PR https://github.com/FoundationDB/fdb-kubernetes-operator/pull/1580.

### Anything else we need to know?

A likely explanation for the number of high number of recoveries is that the transactional system processes are restarting (during the upgrade) at different times (details in the PR mentioned above).

### FDB Kubernetes operator

<details>

```console
$ kubectl fdb version
# paste output here
```

</details>

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

<details>

</details>

**Comment by johscheuer** [comment]
For patch upgrades this might be related: https://github.com/FoundationDB/fdb-kubernetes-operator/pull/1672
