### ISSUE TITLE
Remove sleep in tests in replace_failed_process_groups_test.go

### ISSUE THREAD

**Issue by xumengpanda** [FoundationDB/fdb-kubernetes-operator#1614]
### What would you like to be added/changed?

The taint related test uses sleep to verify that the feature can replace pods on a timely manner. 
Using sleep()  in unit tests is suboptimal because it can slow down the test speed and can become flaky when running on slower hardware. 

Task:
- [ ] We should consider if there is a better way to validate the timing behavior of the taint feature. 
- [ ] We should fix [this flaky test ](https://github.com/FoundationDB/fdb-kubernetes-operator/blob/05f282b84b022ec18d866ba30b1e5816a345e697/controllers/replace_failed_process_groups_test.go#L611-L620).

**Comment by johscheuer** [comment]
This was already fixed.
