### ISSUE TITLE
Operator should include processes based on IP address and IP address and port pair

### ISSUE THREAD

**Issue by johscheuer** [FoundationDB/fdb-kubernetes-operator#1665]
### What would you like to be added/changed?

Currently the operator uses the IP address to include processes once the according resources are removed. If a human operator does a manual exclusion and then triggers a replacement through the operator, the operator will do the "clean up" of the exclusion lit by including the IP address again. If a human operator uses the IP address, port pair the operator will not be doing the clean up. We should improve this and let the operator include both the IP address and the IP address port pair if present.

**Comment by brownleej** [comment]
Is this something we've observed in practice? I see code in fdbcli to handle port-level exclusions when doing an ip-level inclusion, so it may be behaving correctly as-is: https://github.com/apple/foundationdb/blob/main/fdbcli/IncludeCommand.actor.cpp#L95.

**Comment by johscheuer** [comment]
Haven't seen this. Let me check this and close this issue.

Thanks for the pointer 👍
