### ISSUE TITLE
Automatically setting the backup version based on the cluster version

### ISSUE THREAD

**Issue by brownleej** [FoundationDB/fdb-kubernetes-operator#168]
The backup agents need to have their FDB version synced to the version of FDB that the cluster is running in order to make progress with the backup. We currently require that these two versions be configured independently. Instead, we should have the reconciliation for the backup use the cluster's version if the backup's version is unspecified, and the reconciliation for the cluster should automatically set the reconciliation for the backup during upgrades.

**Comment by johscheuer** [comment]
Closing: https://github.com/FoundationDB/fdb-kubernetes-operator/pull/607#issuecomment-822708694
