### ISSUE TITLE
Cluster unhealthy during coordinator change

### ISSUE THREAD

**Issue by iyuroch** [FoundationDB/fdb-kubernetes-operator#1746]
### Description

We were running foundationdbcluster without dedicated coordinator nodes, after change to add separate coordinator nodes a lot of processes in cluster went to being unhealthy.
From what I understand following events happened:
1. fdb operator track coordinator change 
2. update dynamic conf
3. fdbmonitor to restart processes almost at the same time (inotify event connfile changed)

Is this correct chain of events? Is there a need to restart in case of this change? Can we somehow improve so that such change will not cause disruption?

**Comment by johscheuer** [comment]
Per default the fdbmonitor conf has this change:

**Comment by johscheuer** [comment]
Have you verified if the process start time has actually changed?

**Comment by iyuroch** [comment]
@johscheuer I've checked and it seems that there is some other issue not related to fdbmonitor, I'll play with it a bit more. Thanks!

**Comment by johscheuer** [comment]
I would expect that the coordinator change will trigger a recovery in the FDB cluster.

**Comment by iyuroch** [comment]
From my experiments earlier recovery is very fast process, and we have failing queries for some time (couple minutes), there is no new pod scheduled for cluster during that time, so not related to fdbmonitor/recovery. I'll dig into this later, thanks for jumping in so fast.
