### ISSUE TITLE
Cannot add helm repo

### ISSUE THREAD

**Issue by aragastmatb** [FoundationDB/fdb-kubernetes-operator#1788]
### What happened?

Trying to use helm charts from readme.md:
`helm repo add fdb-kubernetes-operator https://foundationdb.github.io/fdb-kubernetes-operator/`

Got this error:
Error: looks like "https://foundationdb.github.io/fdb-kubernetes-operator/" is not a valid chart repository or cannot be reached: failed to fetch https://foundationdb.github.io/fdb-kubernetes-operator/index.yaml : 404 Not Found

### What did you expect to happen?

Repo successfully added

### How can we reproduce it (as minimally and precisely as possible)?

Run `helm repo add fdb-kubernetes-operator https://foundationdb.github.io/fdb-kubernetes-operator/`

### FDB Kubernetes operator

doesn't matter

### Kubernetes version

doesn't matter

### Cloud provider

doesn't matter

**Comment by johscheuer** [comment]
Thanks for your issue, we have to investigate this and resolve the underlying issue.

**Comment by johscheuer** [comment]
We currently don't have the capacity to fix that. Maybe @ammolitor if you got an idea what the problem might be.

**Comment by busser** [comment]
I'm willing to help fix this. Having the chart hosted in a repository somewhere is really convenient. Currently our only choice is to fork the chart into our gitops repo. Having a repository of versioned charts would make maintenance much easier (eg: keeping up with releases can be automated).

Issue #163 was recently closed but it seems like it was supposed to address this problem. The issue mentions the [chart-releaser-action](https://github.com/helm/chart-releaser-action), which pushes charts to a separate branch on the same repo, with that branch being served by Github Pages. Would you be open to that?

**Comment by ammolitor** [comment]
Issue #163 was closed as not to be fixed. We do not have any plans to host the helm charts. We also do not actively test them. I feel that hosting the charts would lead to a false sense of support/stability.

I think your current solution is probably the most appropriate at this time.

**Comment by busser** [comment]
Understood 👍

How would you feel about removing the helm option from the README then?

**Comment by johscheuer** [comment]
We will remove that section from the documentation.

**Comment by busser** [comment]
PR to that effect: #1969

**Comment by busser** [comment]
My bad, I didn't see your PR @johscheuer. Closing mine :)
