### ISSUE TITLE
Cannot upgrade to 7.1

### ISSUE THREAD

**Issue by iyuroch** [FoundationDB/fdb-kubernetes-operator#1814]
### What happened?

After changing version from 6.3 -> 7.1 of database I have following part of the error message:
error while loading shared libraries: libcurl.so.4: cannot open shared object file: No such file or directory

### What did you expect to happen?

To finish upgrade

### How can we reproduce it (as minimally and precisely as possible)?

Setup fdbcluster with version 6.3 and foundationdb/fdb-kubernetes-operator:v1.23.0 operator version, upgrade to 7.1
Sidecar image version 7.1.35

### Anything else we need to know?

I'll be happy to contribute to Dockerfile

### FDB Kubernetes operator

<details>

```console
$ kubectl fdb version
# paste output here
```

</details>

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

<details>

</details>

**Comment by johscheuer** [comment]
This is not an issue with the operator but rather with FDB itself (or rather how it was build). This PR fixed the issue: https://github.com/apple/foundationdb/pull/8226. Since 7.1.37 the AWS SDK support was enabled per default but libcurl was not statically linked. Please us 7.1.39.

**Comment by iyuroch** [comment]
Thanks!
