### ISSUE TITLE
three_data_hall - fault domain check for storage requires 4 replicas

### ISSUE THREAD

**Issue by simenl** [FoundationDB/fdb-kubernetes-operator#1861]
### What happened?

When running with redundancy_mode: 'three_data_hall', the cluster is unable to remove processes.

Relevant logs from the operator:
{"level":"info","ts":"2023-10-24T12:07:02Z","logger":"controller","msg":"Fault domain check for storage subsystem failed","namespace":"simenl2","cluster":"primary-cluster","reconciler":"controllers.removeProcessGroups","error":"team tracker in primary has 3 replicas left but we require more than 4"}
{"level":"info","ts":"2023-10-24T12:07:02Z","logger":"controller","msg":"Reconciliation terminated early","namespace":"simenl2","cluster":"primary-cluster","subReconciler":"controllers.removeProcessGroups","requeueAfter":30,"message":"Removals cannot proceed because cluster has degraded fault tolerance"}

### What did you expect to happen?

The operator should be able to remove processes/pods when the cluster is healthy, with 3 replicas of storage, when the cluster is running with three_data_hall redundancy.

### How can we reproduce it (as minimally and precisely as possible)?

Set up a cluster with three_data_hall replication [[guide](https://github.com/FoundationDB/fdb-kubernetes-operator/blob/7ecfa35516ee77dd33f5111116ed522a9d0dd2f5/docs/manual/fault_domains.md?plain=1#L101)].

Edit `spec.processCounts.log` or `spec.processCounts.storage` with a decreased number in any of the FoundationDB cluster resources.
E.g. through `kubectl edit fdb sample-cluster-az1`

### Anything else we need to know?

HasDesiredFaultToleranceFromStatus [[source](https://github.com/FoundationDB/fdb-kubernetes-operator/blob/7ecfa35516ee77dd33f5111116ed522a9d0dd2f5/pkg/fdbstatus/status_checks.go#L338)] ->
DoStorageServerFaultDomainCheckOnStatus [[source](https://github.com/FoundationDB/fdb-kubernetes-operator/blob/7ecfa35516ee77dd33f5111116ed522a9d0dd2f5/pkg/fdbstatus/status_checks.go#L338)]->
MinimumFaultDomains [[source](https://github.com/FoundationDB/fdb-kubernetes-operator/blob/7ecfa35516ee77dd33f5111116ed522a9d0dd2f5/api/v1beta2/foundationdb_database_configuration.go#L704)]

MinimumFaultDomains is set to 4 for three_data_hall, but three_data_hall will have three replicas of storage (one per data hall). NB logs will have four replicas.

### FDB Kubernetes operator

Operator built from commit be14c23

### Kubernetes version

1.26

### Cloud provider

GCP

**Comment by johscheuer** [comment]
Looking through the code, I believe the correct fix is to change https://github.com/FoundationDB/fdb-kubernetes-operator/blob/7ecfa35516ee77dd33f5111116ed522a9d0dd2f5/api/v1beta2/foundationdb_database_configuration.go#L704 to return `3` for three data hall. The `MinimumFaultDomains` is only used in the context of the number of storage replicas and the number of coordinators (if the cluster is not in HA config or three data hall).

If you have time to raise a PR for this fix, including some additional (unit) testing, I'm more than happy to review the PR.
