### ISSUE TITLE
Three data hall replication - limit concurrent deletions

### ISSUE THREAD

**Issue by simenl** [FoundationDB/fdb-kubernetes-operator#1872]
### What would you like to be added/changed?

When running a cluster with three data hall redundancy [[doc](https://github.com/FoundationDB/fdb-kubernetes-operator/blob/main/docs/manual/fault_domains.md#three-data-hall-replication)], changing a configuration (e.g. cpu request) that triggers the [deletion strategy](https://github.com/FoundationDB/fdb-kubernetes-operator/blob/main/docs/manual/replacements_and_deletions.md#replacements-and-deletions) across all three `fdb/foundationdbcluster` k8s resources, can cause loss of availability. This happens as the operator deletes and recreates a storage pod for each `fdb` k8s resource at the same time.

Ideally the operator would understand that the `fdb` k8s resources correspond to a single fdb cluster, and only apply a single concurrent delete/recreate across the three `fdb` k8s resources.

**Comment by johscheuer** [comment]
This should already be the case: https://github.com/FoundationDB/fdb-kubernetes-operator/blob/main/controllers/update_pods.go#L301-L308 the operator takes a lock before deleting Pods. Are you able to share the logs of the operator instances and the configuration of the cluster(s)?

**Comment by simenl** [comment]
Thanks for the pointer! It seems like locking is disabled by default in my case.

`NewRealLockClient` returns a lock client with locking disabled when ShouldUseLocks is false  [[source](https://github.com/FoundationDB/fdb-kubernetes-operator/blob/main/fdbclient/lock_client.go#L386-L388)]. Which is the case when `LockOptions.DisabledLocks` is not set and not running a multi-kubernetes or multi-region cluster [[source](https://github.com/FoundationDB/fdb-kubernetes-operator/blob/main/api/v1beta2/foundationdbcluster_types.go#L1913-L1920)].

I've just tested with explicitly setting `disableLocks` to `false`
```
spec:
  lockOptions: 
    disableLocks: false
```
and the updates have the desired behaviour of only one concurrent deletion. 🎉 

Perhaps locking should be enabled by default when `RedundancyMode = "three_data_hall"`
