### ISSUE TITLE
Making certain fields on a backup immutable

### ISSUE THREAD

**Issue by brownleej** [FoundationDB/fdb-kubernetes-operator#191]
We have two fields on the backup that cannot be reasonably changed: the cluster name and the backup name. We should add a validation hook to prevent these fields from being changed.

**Comment by johscheuer** [comment]
Once implemented this could also be interesting without a validation hook: https://github.com/kubernetes/enhancements/blob/master/keps/sig-api-machinery/20190603-immutable-fields.md
