### ISSUE TITLE
maxConcurrentReplacements causing deletion update strategy

### ISSUE THREAD

**Issue by simenl** [FoundationDB/fdb-kubernetes-operator#1918]
### What happened?

As a mitigation to storage roles being recruited to log processes [[forum post](https://forums.foundationdb.org/t/never-assign-storage-role-to-log-processes/4294)], we tried setting [maxConcurrentReplacements](https://github.com/FoundationDB/fdb-kubernetes-operator/blob/73270bac4f6fa7faab4f7820c64c618d5a5f1b11/docs/manual/replacements_and_deletions.md?plain=1#L27) to reduce the number of concurrent exclusions.
However, this caused the [Deletion strategy](https://github.com/FoundationDB/fdb-kubernetes-operator/blob/73270bac4f6fa7faab4f7820c64c618d5a5f1b11/docs/manual/replacements_and_deletions.md?plain=1#L27) to incorrectly be applied on the remaining processes, for updates that requires the Replacement strategy. Consequently this resulted in unschedulable pods, as we updated the node selector to an availability zone incompatible with the existing persistent volume on the process.

### What did you expect to happen?

Processes that requires replacement, should not be eligible for the delete update strategy. Even if they were not selected for replacement (yet) due to maxConcurrentReplacements.

### How can we reproduce it (as minimally and precisely as possible)?

1. Create a foundationdb cluster with `maxConcurrentReplacements` and multiple storage pods/processes:
```
spec:
  automationOptions:
    maxConcurrentReplacements: 1
```

2. Make an update to the CRD that requires a [replacement](https://github.com/FoundationDB/fdb-kubernetes-operator/blob/dcefba04c87dbdbc4a9ca9aeacc098da1eb56a89/docs/manual/replacements_and_deletions.md?plain=1#L18). E.g. changing the the node selector.

3. Observe that some of the storage pods will be updated through the delete update strategy

### FDB Kubernetes operator

We run FoundationDB on kubernetes through the [fdb-kubernetes-operator: v1.28.1](https://github.com/foundationDB/fdb-kubernetes-operator).
FoundationDB version: [7.1.43](https://github.com/apple/foundationdb/blob/main/documentation/sphinx/source/release-notes/release-notes-710.rst#7143)

### Kubernetes version

version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.7-gke.500"}

### Cloud provider

GCP

**Comment by johscheuer** [comment]
Thanks for the report, do you think you are able to work on a fix and test for this?

**Comment by simenl** [comment]
Yes 👍 
I'm thinking of reusing the checks from [ReplaceMisconfiguredProcessGroups](https://github.com/FoundationDB/fdb-kubernetes-operator/blob/e2e34fe3b2899e3409949ccf9b7b0c2c7784c39a/internal/replacements/replacements.go#L42)  in [getPodsToUpdate](https://github.com/FoundationDB/fdb-kubernetes-operator/blob/e2e34fe3b2899e3409949ccf9b7b0c2c7784c39a/controllers/update_pods.go#L160). Does that seem sound?

**Comment by johscheuer** [comment]
That sounds reasonable 👍

**Comment by johscheuer** [comment]
Hello @simenl, just wanted to see how things are going on and if you're able to work on a fix for this?

**Comment by simenl** [comment]
Hi @johscheuer, 
sorry, I got caught up with other things.

I've put up a draft: https://github.com/FoundationDB/fdb-kubernetes-operator/pull/1954
