### ISSUE TITLE
FDB operator stuck without recreating pods

### ISSUE THREAD

**Issue by johscheuer** [FoundationDB/fdb-kubernetes-operator#1931]
### What happened?

See: https://forums.foundationdb.org/t/fdb-operator-stuck-without-recreating-pods/4287

### What did you expect to happen?

Operator should recreate Pods again.

### How can we reproduce it (as minimally and precisely as possible)?

-

### FDB Kubernetes operator

<details>

```console
$ kubectl fdb version
# paste output here
```

</details>

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

<details>

</details>

**Comment by gm42** [comment]
@johscheuer with v1.33.0 I can still see the issue :thinking: but my changes in https://github.com/FoundationDB/fdb-kubernetes-operator/pull/1949 for some reason manage to bring back the cluster in usable state. I can dig deeper, as needed.

**Comment by johscheuer** [comment]
Can you give some more context on what exactly you are testing, e.g. FDB version and configuration and how your test setup differs from: https://github.com/FoundationDB/fdb-kubernetes-operator/pull/1932/files#diff-bf18d716f2270f262c78ecefa1b927897ae81e92cb85e969cde2010ef29acb1dR1898.

**Comment by gm42** [comment]
> Can you give some more context on what exactly you are testing, e.g. FDB version and configuration and how your test setup differs from: https://github.com/FoundationDB/fdb-kubernetes-operator/pull/1932/files#diff-bf18d716f2270f262c78ecefa1b927897ae81e92cb85e969cde2010ef29acb1dR1898.

Sure, I should be able to provide this later today :crossed_fingers:

**Comment by gm42** [comment]
@johscheuer I did some testing and v1.33.0 works when the pods of all coordinators or just some coordinators are deleted. :tada: 

However the coordinator pods in my case take ~5 minutes or more to go into `Running` state, so the operator gives up earlier than that, failing reconciliation. On next reconciliation run it manages to correctly reconcile it.

Would it be an idea to make the operator react to pods transitioning state in this case, or is that something already tried?

**Comment by johscheuer** [comment]
Are you able to share the logs of your tests to see where the operator spend its time? We haven't optimised for this specific case and I'm not sure how much that will help as most of the time it's not the operator reconciliation speed but rather Kubernetes bringing up the Pods. If you have any specific ideas or you think this is something that should get some attention, feel free to open an issue and we can see what we can tune.

Thanks for the feedback! :)

**Comment by gm42** [comment]
Sure, it takes ~9 minutes from the deletion of 2/3 coordinator pods till reconciliation, starting from an already-reconciled cluster.

The pod was in pending state for ~6 minutes and 45 seconds (estimated using metrics); so I think it's still a good result, I was wondering if it is already acting on the events or on some sort of timer, forgive my ignorance about this part.

[operator-reconciling.log](https://github.com/FoundationDB/fdb-kubernetes-operator/files/14494005/operator-reconciling.log)
