### ISSUE TITLE
Improving support for prerelease FDB versions in the Kubernetes operator

### ISSUE THREAD

**Issue by brownleej** [FoundationDB/fdb-kubernetes-operator#200]
We recently added some special behavior to the post-upgrade version check to support pre-release binaries, which represent themselves differently in the cluster status. This was a quick hack to allow us to test with pre-release versions, but we should think more about what we need to fully support testing against pre-release versions. For instance, we should look into applying the check for the `-PRERELEASE` suffix more selectively, using version syntax that clarifies that the version is a pre-release, and having a way to download the CLI within the operator dynamically to support nightly builds.

**Comment by johscheuer** [comment]
@brownleej do you think https://github.com/FoundationDB/fdb-kubernetes-operator/issues/1012 solved this issue?
