### ISSUE TITLE
cluster health status indicators did not meet expectations.

### ISSUE THREAD

**Issue by catpineapple** [FoundationDB/fdb-kubernetes-operator#2086]
### What happened?

hi, when I was doing a simple deployment test, I found that the cluster health status indicators did not meet expectations. This situation is likely to happen. Is it because I am missing the necessary configuration of CRD or because of abnormal behavior of fdb-operator?
<img width="1950" alt="image" src="https://github.com/FoundationDB/fdb-kubernetes-operator/assets/42031973/56484be0-9998-4da1-ae59-51103bdb0a01">

### What did you expect to happen?

 The command return result of 'kubectl get fdb  -oyaml ' contains accurate information about 'status.health'

### How can we reproduce it (as minimally and precisely as possible)?

k8s cluster build by kind : kind create cluster --image=kindest/node:v1.25.11
then:

kubectl apply -f https://raw.githubusercontent.com/FoundationDB/fdb-kubernetes-operator/main/config/crd/bases/apps.foundationdb.org_foundationdbclusters.yaml
kubectl apply -f https://raw.githubusercontent.com/FoundationDB/fdb-kubernetes-operator/main/config/crd/bases/apps.foundationdb.org_foundationdbbackups.yaml
kubectl apply -f https://raw.githubusercontent.com/FoundationDB/fdb-kubernetes-operator/main/config/crd/bases/apps.foundationdb.org_foundationdbrestores.yaml
kubectl apply -f https://raw.githubusercontent.com/foundationdb/fdb-kubernetes-operator/main/config/samples/deployment.yaml
kubectl apply -f https://raw.githubusercontent.com/foundationdb/fdb-kubernetes-operator/main/config/samples/cluster.yaml

### FDB Kubernetes operator

<details>

```console
$ kubectl fdb version
# paste output here
```

</details>

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: v1.29.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.25.11
WARNING: version difference between client (1.29) and server (1.25) exceeds the supported minor version skew of +/-1
```

</details>

### Cloud provider

<details>
cloud.tencent.com
</details>

**Comment by johscheuer** [comment]
Are you able to share the operator logs?

**Comment by johscheuer** [comment]
I'm going to close this issue. Feel free to reopen it once you have the operator logs to share.
