### ISSUE TITLE
Reconciliation stuck with long command lines

### ISSUE THREAD

**Issue by brownleej** [FoundationDB/fdb-kubernetes-operator#2105]
### What happened?

When adding additional peer verification rules, I saw a cluster get stuck in a loop of trying to bounce processes. The processes were getting bounced because the operator saw their command line as being incorrect. The command line was truncated at 10,000 characters, so the operator never saw the command line it expected.

### What did you expect to happen?

I expected the operator to update the command line for the processes.

### How can we reproduce it (as minimally and precisely as possible)?

1. Create a cluster
2. Add 100 peer verification rules with 100 characters in each one

### FDB Kubernetes operator

<details>

```console
$ kubectl fdb version
foundationdb-operator: 1.43.0
kubectl-fdb: 1.43.0
```

</details>

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

<details>

</details>

**Comment by johscheuer** [comment]
If the command line is truncated, that sounds more like a limitation from FDB than the operator. I take a look to see how we can work around this.
