### ISSUE TITLE
Customizing the prefix that the operator uses for lock data

### ISSUE THREAD

**Issue by brownleej** [FoundationDB/fdb-kubernetes-operator#234]
The operator has a hardcoded prefix for the keys where it stores lock data in the database. We should allow customizing this to support users who have a data model that conflicts with our default prefix.

**Comment by johscheuer** [comment]
This should be resolved with: https://github.com/FoundationDB/fdb-kubernetes-operator/blob/master/docs/cluster_spec.md#lockoptions? If not please reopen the issue.
