### ISSUE TITLE
Taking locks when including instances

### ISSUE THREAD

**Issue by brownleej** [FoundationDB/fdb-kubernetes-operator#238]
When we are including instances, we should take a lock to prevent overlap between instances of the operator. Instances that are not able to get the lock should submit their inclusion list so that the lock owner can aggregate them and include everything in one go.

**Comment by johscheuer** [comment]
@brownleej I think you solved this in https://github.com/FoundationDB/fdb-kubernetes-operator/pull/491?

**Comment by brownleej** [comment]
I don't think we did anything with the inclusion commands in that PR. I checked the action that includes instances, and it's not doing anything with locks. The description is out-of-date, since we've removed the idea of aggregating operations from the scope of most lock-based operations, but we may still want to get a lock before including instances.
