### ISSUE TITLE
Allowing database configuration changes when a cluster is unhealthy because of connection string issues

### ISSUE THREAD

**Issue by brownleej** [FoundationDB/fdb-kubernetes-operator#244]
If a cluster has a client that cannot write its cluster file, it reports itself as unhealthy. This blocks configuration changes through the operator, even though there's no relationship between the configuration change and the problem with the cluster health. I think we should look for a more nuanced way of checking whether a cluster is healthy enough to accept configuration changes.

**Comment by rbtcollins** [comment]
I have seen the operator self-inflict this on itself: that is the only client that couldn't update itself was the operator client.
