### ISSUE TITLE
Setting the log dir and log group through environment variables in our pods

### ISSUE THREAD

**Issue by brownleej** [FoundationDB/fdb-kubernetes-operator#245]
We set the log dir and log group through parameters to the fdbserver process. This allows us to send logs to an emptyDir volume that users can attach additional containers to for log forwarding. If someone execs into a pod and runs an fdbcli command, it doesn't generate any trace logs at all. I think it would be better for us to set the log dir and log group through environment variables. This would allow fdbcli commands from the server pods to get logged to the same directory, and get picked up by log management with no additional action on the user's part.

**Comment by johscheuer** [comment]
I changed the label. It probably makes sense to adjust this for the new unified image and make this the default for the unified image.
