### ISSUE TITLE
Reconciliation getting stuck when replacing a pod without an IP

### ISSUE THREAD

**Issue by brownleej** [FoundationDB/fdb-kubernetes-operator#246]
If a pod is stuck waiting to be scheduled, we want to be able to replace it to get the cluster back to a healthy state. If we try to replace it through the operator, it will get stuck at the ChooseRemovals step. I think the reason it's getting stuck is because this step needs to associate the pod name with an IP address for the exclusions, and that's not possible until the pod is scheduled.

I think if the pod is unscheduled the best course of action is to ignore it for the purposes of exclusions. Eventually we will be able to exclude instances by instance ID, which will be safer than using IPs and will avoid this whole problem. In the mean time, we need to be able to get out of these kind of bad situations.

We may be able to add an additional check where we look in the status JSON for any pod that matches the pod name, but we'll need to make sure we can handle pods in different KCs that may have the same pod name.

**Comment by rbtcollins** [comment]
We've seen this too, sometimes with new clusters where we didn't size it quite right, othertimes where we are reshaping a cluster and realise we don't have quite the resources and need to do something different. Being able to change our minds mid-reshape would be great.
