### ISSUE TITLE
Customization of pods per process doesn't work

### ISSUE THREAD

**Issue by v-pap** [FoundationDB/fdb-kubernetes-operator#251]
After following the examples in the operator's README, I was expecting all the fdb pods to follow the limits and requests set by the sample cluster (https://raw.githubusercontent.com/foundationdb/fdb-kubernetes-operator/master/config/samples/cluster_local.yaml). This was not the case. Here is how a pod was configured by applying the sample cluster:
```
kubectl describe po sample-cluster-storage-1 | grep -A 5 Limits
    Limits:
      cpu:     1
      memory:  1Gi
    Requests:
      cpu:     1
      memory:  1Gi
```
I even tried to redeploy the cluster with different limits and requests for different kinds of processes with no effect. Also it would be nice to include the restore crd in the example like: `(kubectl create -f https://raw.githubusercontent.com/FoundationDB/fdb-kubernetes-operator/master/config/crd/bases/apps.foundationdb.org_foundationdbrestores.yaml) || (kubectl replace -f https://raw.githubusercontent.com/FoundationDB/fdb-kubernetes-operator/master/config/crd/bases/apps.foundationdb.org_foundationdbrestores.yaml)` since it is required in order to deploy the fdb cluster.

**Comment by brownleej** [comment]
We changed the way the resource customization works, and it may be that the version of the operator you're running doesn't support the field we're using in that example. You might want to building the operator from the main branch and checking if it works on that version of the operator and the CRD.

**Comment by v-pap** [comment]
Is the fdb kubernetes operator image up-to-date with the latest release? I am just asking that because this change in the customization options is included, if I am not mistaken, in the 0.12.0 release which was created 2 weeks ago.

**Comment by brownleej** [comment]
You're right. That should have gone out in the last release. I was mistaking it for another issue. I'll take a look at this and see if I can reproduce the issue and get to the bottom of it.

**Comment by brownleej** [comment]
I just ran a test of this with the v0.12 operator and the YAML file you linked, and this is the output I saw:

    kubectl describe pod sample-cluster-storage-1 | grep -A 5 Limits
        Limits:
          cpu:     250m
          memory:  128Mi
        Requests:
          cpu:     250m
          memory:  128Mi

**Comment by v-pap** [comment]
So, I updated the image of the operator from 0.12.0 to the 0.13.0, and the problem seems to be resolved.
