### ISSUE TITLE
volumeClaim vs volumeClaimTemplate

### ISSUE THREAD

**Issue by rbtcollins** [FoundationDB/fdb-kubernetes-operator#263]
perhaps you'd be open to renaming volumeClaim to volumeClaimTemplate to match [statefulset](https://v1-15.docs.kubernetes.io/docs/reference/generated/kubernetes-api/v1.15/#statefulsetspec-v1-apps) ?

The claim isn't actually meant to reference an existing singular claim, and naming it as a template would help with the ergonomics of the operator.

**Comment by brownleej** [comment]
Yeah, that seems reasonable.

**Comment by rbtcollins** [comment]
I haven't looked closely at the configMap part of the document yet; but if it forms a template from which N different config maps are created, I would certainly agree.

However my understanding so far has been that there is one configMap per cluster; and the templatish nature is more to do with fields being filled in. I guess it is a little more ambiguous?

**Comment by brownleej** [comment]
Yes, that's an accurate description of how the config map field is used. I agree it's a little more ambiguous there.
