### ISSUE TITLE
reconciliation seems to not be event driven

### ISSUE THREAD

**Issue by rbtcollins** [FoundationDB/fdb-kubernetes-operator#265]
reconciliation seems to be timer driven not event driven. I'll probably end up filing a few might-be-duplicate bugs as a result - sorry if they are, but in case they aren't I'd rather be thorough.

When stuck waiting for a pod to schedule etc the reconciler backs off and waits, sometimes up to 10 minutes; but this can mean the cluster doesn't progress even though the pod has been running for well, 10 minutes.

Adding a controller that tickles reconciliation when pods change state would allow this to be edge triggered as well as timer based.

Observe the timestamps here:
```
2020-06-19T00:49:02.549Z        INFO    controller      Retrying reconcilation  {"reason": "Waiting for pod fdb-test/fdb-test-cluster/fdb-test-cluster-log-12 to be assigned an IP"}
2020-06-19T00:59:57.910Z        INFO    controller      Running command {"namespace": "fdb-test", "cluster": "fdb-test-cluster", "path": "/usr/bin/fdb/6.2/fdbcli", "args": ["/usr/bin/fdb/6.2/fdbcli", "--exec", "status json", "-C", "/tmp/512495387", "--log", "--timeout", "30", "--log-dir", "/var/log/fdb"]}
```

The thing that is particularly annoying is when autoscale nodes are involved and the fdb operator is slowing down at the same time as capacity comes online, leading to spurious extra delays.

This is distinct to #246, which is observing reasonably that some state changes can proceed when a pod isn't scheduled or running, and is instead about reacting promptly when a pod does get scheduled. (And/or go ready)

**Comment by brownleej** [comment]
Reconciliation is driven by events on the cluster object, but not on events on any dependent objects. If there's a pattern for operators driving events off of pods as well as their custom resources, it would make sense for us to follow it. We could also make this better by controlling the reconciliation backoff more tightly, which I think requires changes in kubebuilder.

**Comment by rbtcollins** [comment]
High level what you want is a single work queue (to avoid races), and then any number of events feeding into that. So multiple sharedindexedinformers tied into the one work queue. You can get multiple edge events for a single object today (e.g. someone edits the spec rapidly); this pattern just makes that happen potentially more often.

Generally speaking you should watch any object that you control: you control some pvcs, you should watch those; ditto pods. You don't own pv's, so you shouldn't watch those. You control the cluster specs, though it is shared with the operator, so you should watch those.

Let me know if thats clear-as-mud :P.

**Comment by johscheuer** [comment]
@brownleej I think your PR https://github.com/FoundationDB/fdb-kubernetes-operator/pull/322 has resolved this issue?

**Comment by rbtcollins** [comment]
That does look good, thanks. I think we can just close this, though I'll reopen if there are remaining issues.
