### ISSUE TITLE
No mechanism for deleting nodes, only recreating pods

### ISSUE THREAD

**Issue by rbtcollins** [FoundationDB/fdb-kubernetes-operator#267]
The documented mechanism for excluding a pod and recreating it doesn't delete the PVC, and operates effectively synchronously, with no window for an admin to delete the PVC.

Why does this matter? We have some clusters running with node local storage using the local-static-provisioner. This is configured to break up a node-local 1.78TB NVMe drive into 8x210G partitions, one per core, and then we run 8 FDB processes on the node.

All good until we need to dispose of the node gracefully: at this point the state machine we want to run through is:
- cordon the node
- exclude the pods
- delete pod
- *delete PVC*
- create the PVC
- create the pod (which will now schedule onto a new node

We need to dispose of nodes gracefully to meet maintenance requirements from AKS, or to upsize our clusters - to meet fault domain mapping limitations we have limits on the number of machines so need to migrate to larger machines as we scale.

I'm not sure what makes sense here - a flag on the cluster informing the operator that this storage class is node-local, or a different exclusion collection that operates differently? I note that the automated scale-down logic seems to delete the PVC, so perhaps the odd thing here is that the admin capability of 'reboot a node gracefully' was layered in here and special cased in some way to *not* delete the PVC (it doesn't - I don't know why yet, I haven't traced the code).

**Comment by brownleej** [comment]
You should be able to replace the instance by adding it to the instancesToRemove list in the spec. That would take the following steps:

* Create the new PVC
* Create the new pod, which will schedule onto a new node if you've already cordoned the old node.
* Exclude the old pod
* Delete pod
* Delete PVC

That should leave you with a similar state to the one you're looking for, though the instance ID for the new pod will be different. It will also avoid any degradation in capacity while you are doing the exclusion, and likely give you better data distribution because the data movement from the exclusion can make use of the new PVC. The cost of that is a temporary increase to the resource requirements while you are running the old and new pod at the same time.

Does that flow make sense for your use case?

**Comment by rbtcollins** [comment]
The observed behaviour when:
- cordon the node
- add the pod to instancesToRemove is:
- the pod is removed
- the PVC is not removed
- the new pod is created
- the new pod cannot schedule successfully
   - because the old PV is still bound by the undeleted PVC
      - and that PV has a topology key binding it to the cordoned node

I tried adding a new storage node / log node to the spec and simultaneously excluding existing nodes, but this didn't change the behaviour for the existing nodes

But perhaps I have misinterpreted something; I will gather a full log in detail to avoid any misunderstandings.

Re: resource requirements - thats fine; for the case where we're evacuating a node, we always have a new node to move to, with new local disks.

**Comment by johscheuer** [comment]
@rbtcollins could you verify the behaviour with the current operator version? I did a small test and everything looks fine when I add the instance to `instancesToRemove`:


```bash
kubectl get  pvc -w
NAME                            STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
data-minio-0                    Bound    pvc-8734cc03-ce67-418b-bb41-c0606e724c23   10Gi       RWO            hostpath       11d
sample-cluster-log-1-data       Bound    pvc-7d383be5-c8c5-4016-a30b-309f792b60b3   16G        RWO            hostpath       92s
sample-cluster-log-2-data       Bound    pvc-12d596a7-a864-49ba-a67b-4b17f34f8d34   16G        RWO            hostpath       92s
sample-cluster-log-3-data       Bound    pvc-162bd9c4-2842-41c7-aaac-a19d588b6442   16G        RWO            hostpath       91s
sample-cluster-log-4-data       Bound    pvc-4b21fc8f-2c2d-410c-b105-6051982f241d   16G        RWO            hostpath       91s
sample-cluster-storage-1-data   Bound    pvc-afd2cfa1-fae3-4fc0-8ab5-25be73f25275   16G        RWO            hostpath       92s
sample-cluster-storage-2-data   Bound    pvc-1c3e25c3-c50d-4007-b4a4-5abfb679acbd   16G        RWO            hostpath       92s
sample-cluster-storage-3-data   Bound    pvc-7120a82a-5cc9-4138-beba-f0f4c9d9772f   16G        RWO            hostpath       92s
sample-cluster-storage-4-data   Pending                                                                        hostpath       0s
sample-cluster-storage-4-data   Pending                                                                        hostpath       0s
sample-cluster-storage-4-data   Pending   pvc-fa804c9b-de2b-405e-95d6-08936fad44c1   0                         hostpath       0s
sample-cluster-storage-4-data   Bound     pvc-fa804c9b-de2b-405e-95d6-08936fad44c1   16G        RWO            hostpath       0s
sample-cluster-storage-1-data   Terminating   pvc-afd2cfa1-fae3-4fc0-8ab5-25be73f25275   16G        RWO            hostpath       112s
sample-cluster-storage-1-data   Terminating   pvc-afd2cfa1-fae3-4fc0-8ab5-25be73f25275   16G        RWO            hostpath       2m33s
```

**Comment by johscheuer** [comment]
Friendly ping @rbtcollins

**Comment by rbtcollins** [comment]
sorry, on my todo list!

**Comment by johscheuer** [comment]
We added a subcommand to the `kubectl fdb` plugin to "drain/cordon" a set of nodes, so this might be useful for you in this case: https://github.com/FoundationDB/fdb-kubernetes-operator/tree/master/kubectl-fdb#usage

**Comment by johscheuer** [comment]
@rbtcollins hello again :) Any change that you test the proposed plugin command to see if it solves the problem? If so feel free to close the issue.

**Comment by johscheuer** [comment]
I think we have everything to support the requested feature by either using the `kubectl fdb` plugin or adding all Pods to the remove list and let the operator replace them (the plugin is doing the same steps). If anything should be missing feel free to reopen the issue or create a new one. Thanks!
