### ISSUE TITLE
Enhancement suggestion: permit reserving 5% of disk space

### ISSUE THREAD

**Issue by rbtcollins** [FoundationDB/fdb-kubernetes-operator#273]
It's well known that running out of of disk on storage nodes is a bad idea. Some k8s PV's permit expansion; some permit online expansion. But the general case is that a given sized PV is that size.

One thing we could do that would be very helpful is to reserve 5% of the disk - by allocating a non-sparse file during node bring-up. Then if the cluster *does* run out of disk space and grind to a halt, recovery becomes much much easier:
 - Add new nodes to allow rebalancing to move content somewhere
 - Remove the reservation files on the existing nodes to permit new transactions to happen, so that rebalancing happens
  - Reinstate the reservation files on the nodes as soon as possible (and if the user doesn't quench the incoming traffic during this recovery period - well, we can only help so much...)

We're planning on doing this for our own operational peace of mind - we wedged a test database with out of disk already, and couldn't manage to tickle it into expanding onto new nodes, so wed be happy to contribute code for this, if the idea is acceptable.

**Comment by brownleej** [comment]
I'm not opposed to this, but it seems like something where the database itself needs to be stronger as well. I know that once the database gets to 90% full it starts restricting data movement to avoid making things worse. It should still be possible to get out of this situation, even if it means migrating onto a larger set of servers. It may be worth brining this up on the forums as a more general operational discussion.

**Comment by rbtcollins** [comment]
I agree - but we can't retrofit improvements to fdb to existing releases of it :). Will bring it up on the forums as well.

**Comment by JoshuaMcManus** [comment]
Old issue - closing as not to be fixed.
