### ISSUE TITLE
Having a command to do a hard shutdown of the processes from the Kubernetes sidecar

### ISSUE THREAD

**Issue by brownleej** [FoundationDB/fdb-kubernetes-operator#277]
There may be situations where a machine fails in a way that it is causing problems for the cluster but cannot be cleanly shut down through Kubernetes or cannot be updated through the operator. As an escape hatch, it could be useful to have a command to do a hard shutdown through the operator. This command should update the monitor conf file to have no server entries and shut down the fdbserver process. We should be able to call the API call for updating the monitor conf to restore the full monitor conf and bring back the process.

**Comment by johscheuer** [comment]
Since we are moving to the new sidecar in the longterm, do you think we shouldd keep this open?
