### ISSUE TITLE
Using tini as the PID 1 process for FDB containers

### ISSUE THREAD

**Issue by brownleej** [FoundationDB/fdb-kubernetes-operator#288]
We're currently using a shell as the PID 1 process for the FDB containers that the operator launches. This can cause delays when shutting down the container due to how the shell handles SIGTERM signals. Once we have tini available in the images, we should try using that as the main process instead, and see if that improves our shutdown behavior.

We should also explore the SIGTERM behavior in the sidecar container to make sure that meets our requirements.

**Comment by johscheuer** [comment]
Is this issue obsolete with https://github.com/FoundationDB/fdb-kubernetes-operator/pull/447?

**Comment by brownleej** [comment]
Yes, though we may want to leave the issue open until that design is approved, in case we decide to go in a different direction.
