### ISSUE TITLE
Forcing operator to create an instance with a particular type and ID

### ISSUE THREAD

**Issue by brownleej** [FoundationDB/fdb-kubernetes-operator#309]
There may be weird scenarios where a pod is lost, but the PVC related to that pod stays around, and we want to recover the data from that instance. To support this, I think it would be useful to have an option in the spec to require the operator to create an instance with a given type and instance ID. This should not be counted in the process counts, so that adding an explicit instance creation will not trigger another instance being removed. If an instance is in the pending removals list, or is marked for removal in some other fashion, having it in the explicit instance creation list should still cause the operator to create the pod.

**Comment by johscheuer** [comment]
I would say with the `FoundationDBProcessGroup` that should be pretty simple.
