### ISSUE TITLE
Being able to roll back a failed migration

### ISSUE THREAD

**Issue by brownleej** [FoundationDB/fdb-kubernetes-operator#319]
Once the operator has put instances in its pendingRemovals map, there is no way to remove them from the map other than completing the removal process itself. That can create situations that are hard to get out of. For instance, someone might change the storage class in a way that requires a migration, but find that they don't have enough capacity in their resource quota to create the new pods. The operator will get stuck waiting for the new pods before it can move on with the replacement. Changing the storage class back will make the original pods valid again, but they will still be targeted to removals. At this point it would be safe to give up on those replacements and go back to the original configuration, but there is no way to have the operator do this. Instead, it will try to create new pods with the original storage class, which will fail for the same quota issues.

I think we should have a field in the spec to re-include instances that are in the pending removals list. This should clear the instances from the pendingRemovals list, and re-include them in the database. If there are pods that need to be replaced but are in the explicit re-inclusion list, we can log an error and prevent reconciliation from completing.

**Comment by kcking** [comment]
This would be great to have! Currently we manually `curl` the kubernetes API to remove any invalid pods after cleaning up the resources ourselves

```bash
curl localhost:8001/apis/apps.foundationdb.org/v1beta1/namespaces/default/foundationdbclusters/$FDBCLUSTER/status\
 --header "Content-Type: application/json-patch+json" --request PATCH \
--data "[{\"op\": \"remove\", \"path\": \"/status/pendingRemovals/$POD\"}]"```

**Comment by brownleej** [comment]
There's a further proposal on this in the Automated Replacement design: https://github.com/FoundationDB/fdb-kubernetes-operator/blob/master/docs/design/automatic_replacements.md

**Comment by johscheuer** [comment]
I added this to the `FoundationDBProcessGroup` project since that should simplify the implementation and that's a good use case we should keep in mind implementing the changes.

**Comment by JoshuaMcManus** [comment]
Old issue - closing as not to be fixed.
