### ISSUE TITLE
Getting rid of hardcoded CA in the docker build

### ISSUE THREAD

**Issue by brownleej** [FoundationDB/fdb-kubernetes-operator#327]
Our docker builds include a hardcoded CA for the root CA used by the FoundationDB website. This is a workaround for the fact that this CA is not included in newer releases of the ca-certificates packages. Once the website certificate is fixed, we should remove this hardcoded CA.

**Comment by johscheuer** [comment]
Fixed in: https://github.com/FoundationDB/fdb-kubernetes-operator/commit/119d50a0b4efd2f3d805ff3fab269744af23edef
