### ISSUE TITLE
Safety checks to prevent deleting too many pods at once

### ISSUE THREAD

**Issue by brownleej** [FoundationDB/fdb-kubernetes-operator#351]
Once the operator believes that an exclusion has completed, it will delete all of the excluded pods and PVCs at once. This presents a risk of losing a large number of volumes if the operator has a bug that causes it to mistakenly mark exclusions complete too soon. To mitigate this, we may want to throttle the deletion of pods. By default, we could only delete one pod at a time in the remove_pods step. We could also add a safety check to refuse to delete any pods if the operator is already at degraded fault tolerance.

**Comment by rbtcollins** [comment]
See also #354
