### ISSUE TITLE
Avoid modeling addresses as strings

### ISSUE THREAD

**Issue by brownleej** [FoundationDB/fdb-kubernetes-operator#352]
We have hit multiple bugs due to different parts of the system using different format for addresses. For instance, some parts  use `$ip:$port:$tls`, where others use `$ip:$port`, and others simply use `$ip`. This may suggest a deeper problem of using strings to represent something that deserves a first-class type, with consistent comparison operations and automatic serialization into parts of the system that need a specific form.

**Comment by johscheuer** [comment]
Once https://github.com/FoundationDB/fdb-kubernetes-operator/pull/380 is merged we can revisit the representation. I also did some work in the IPv6 PR https://github.com/FoundationDB/fdb-kubernetes-operator/pull/341 but I think it makes sense to solve this issue first and then add the IPv6 support (should simplify the IPv6 PR and later the Dual-Stack support).
