### ISSUE TITLE
Keeping monitor conf in configmap until all pods of that process class are gone

### ISSUE THREAD

**Issue by brownleej** [FoundationDB/fdb-kubernetes-operator#358]
We only include monitor conf in the config map for processes we are intending to run. This is good in the steady state, as it reduces configuration bloat, but it presents a potential problem when removing processes. If we are removing all processes of a given process class, we drop that configuration from the config map immediately. This causes the pods to fail to mount config map updates because the pod is referencing keys that no longer exist in the config map. That in turn will lead the pod to miss other updates from the config map. It generally shouldn't be necessary for them to retrieve those keys, but I've seen cases where things get stuck on pods like this, and it creates noisy errors that we should avoid. I think we should leave the monitor conf in the config map until we tear down all the pods that would reference that monitor conf.

**Comment by JoshuaMcManus** [comment]
Old issue - closing as not to be fixed.
