### ISSUE TITLE
Prevent operator from re-reconciling in response to its own changes

### ISSUE THREAD

**Issue by brownleej** [FoundationDB/fdb-kubernetes-operator#360]
We currently trigger reconciliation when any part of the cluster resource changes. This can cause us to run reconciliation unnecessarily in response to status changes from the operator itself. If there is a bug causing repeated status updates, this can cause reconciliation to continue forever. We should find a way to avoid responding to these kind of updates.

We can apply filters to only reconcile on certain changes, and there's a built-in one to reconcile only on changes to the spec. We should see if this is a good fit for our needs. We would need to make sure that this doesn't limit our response to status changes on other resources, like pods getting scheduled or terminated. We should also make sure there's a reliable way to manually trigger reconciliation changes in case the operator is stuck in back off and we want to kick-start it.

**Comment by johscheuer** [comment]
We could use: https://pkg.go.dev/github.com/kubernetes-sigs/controller-runtime/pkg/predicate to limit when a reconcile loop will be triggered (also the old link to: https://book-v1.book.kubebuilder.io/beyond_basics/controller_watches.html).
