### ISSUE TITLE
Enabling service IPs by default

### ISSUE THREAD

**Issue by brownleej** [FoundationDB/fdb-kubernetes-operator#390]
We have an experimental feature to use service IPs as the public IP. Once we are confident that this feature is stable, we should consider enabling it by default in order to give stable IPs.

**Comment by johscheuer** [comment]
I would rather explore the way with headless services and the sidecar resolves the DNS entry until FDB supports this case. I think the number of required Service IPs for bigger clusters could be a blocker/surprise for some people.
