### ISSUE TITLE
migration of pods in more cases

### ISSUE THREAD

**Issue by rbtcollins** [FoundationDB/fdb-kubernetes-operator#404]
The docs note that "there are some changes that require a migration regardless of the value of updatepodsbyreplacement..."

https://github.com/FoundationDB/fdb-kubernetes-operator/blob/master/docs/user_manual.md#pod-update-strategy

It would be great to expand the cases where rolling updates can be used: for some private cloud cases, migrations place an enormous pressure on the infrastructure compared to running FDB in a non-kubernetes configuration, and the migration strategy is the primary cause of this.

Techniques like surge pods can be used to avoid degrading fault tolerance without doing a full migration. (Bring in one new pod, reach healthy, exclude one old pod, drop it, loop).

**Comment by johscheuer** [comment]
Related: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/400

**Comment by rbtcollins** [comment]
Argh sorry I didn't realise @simenl had also filed a bug on this. I think these are effectively duplicates.
