### ISSUE TITLE
"change the storage servers per disk" test race

### ISSUE THREAD

**Issue by rbtcollins** [FoundationDB/fdb-kubernetes-operator#405]
In this test BeforeEach and It are not synchronised, so the following sequence can occur:

```
Test-thread: Update
Test-thread: List
Operator: respond
```

This will result in a failed test with the storage pods apparently not updated.

I think a good way to fix this would for an Eventually looking for the operator status writing some status update somewhere, since this is a register ABA update that we're trying to detect (that, or the Eventually needs to actually encompass the full assertion).

**Comment by johscheuer** [comment]
This was fixed as part of https://github.com/FoundationDB/fdb-kubernetes-operator/pull/407 right?

**Comment by johscheuer** [comment]
I think since we refactored our tests and run the race detection this issue is resolved. If you find anything else please reopen it.
