### ISSUE TITLE
Istio support

### ISSUE THREAD

**Issue by funkypenguin** [FoundationDB/fdb-kubernetes-operator#443]
Hi folks!

I intend to use fdb-operator to deploy fdb clusters in istio-protected namespaces. I've been able to deploy the local cluster sample YAML to an ordinary Kubernetes namespace, but when I apply it to a namespace with Istio mTLS (via sidecar injection), the operator can't complete reconcilliation.

I get as far as this:

```
ason": "ChangingCoordinators", "message": "Choosing initial coordinators"}
2020-12-15T01:29:15.366Z	INFO	controller	Reconciliation terminated early	{"namespace": "sandbox", "name": "retort-fdb", "lastAction": "controllers.GenerateInitialClusterFile"}
2020-12-15T01:29:15.366Z	ERROR	controller	Error in reconciliation	{"subReconciler": "controllers.GenerateInitialClusterFile", "namespace": "sandbox", "cluster": "retort-fdb", "error": "HTTP request failed. Status=503; response=upstream connect error or disconnect/reset before headers. reset reason: connection termination"}
github.com/go-logr/zapr.(*zapLogger).Error
```

and the istio-proxy sidecar tells me that in the operator is trying to connect to the first storage pod on port 8080:

```
[2020-12-15T01:29:14.327Z] "GET /substitutions HTTP/1.1" 503 UC "-" "-" 0 95 1 - "-" "Go-http-client/1.1" "63cd1df6-9831-45df-b4ef-557e51d71c70" "10.124.247.186:8080" "10.124.247.186:8080" PassthroughCluster 10.121.52.3:33532 10.124.247.186:8080 10.121.52.3:33530 - allow_any
[2020-12-15T01:29:15.364Z] "GET /substitutions HTTP/1.1" 503 UC "-" "-" 0 95 1 - "-" "Go-http-client/1.1" "521a33c4-2c0d-4a46-90cf-c1c947547833" "10.124.247.186:8080" "10.124.247.186:8080" PassthroughCluster 10.121.52.3:33624 10.124.247.186:8080 10.121.52.3:33530 - allow_any
```

What it _looks_ like is that the operator is relying on IP addressing to identify the pods, rather than DNS name, and this may be causing incompatibilities with Istio.

If I'm understanding this correctly, do you have any suggestions re how to configure an FDB cluster with Istio support?

Thanks!
D

**Comment by johscheuer** [comment]
FDB doesn't support DNS (target is `7.0`) https://github.com/apple/foundationdb/issues/354. The operator itself could workaround this by using the headless Service option and using the Pod DNS entry rather than the IP. But I'm not sure if the cluster would be able to communicate (since all communication will be done with IP addresses). It's a while since I worked with Isitio but I can't remember the limitation to use DNS. If I find some spare time I will do some experiments otherwise feel free to write some docs and create a PR for this. 

- Just to confirm all Pods are part of the mesh (and have the sidecar injected)? 
- Could you create a Service for the Operator (and activate the headless service option https://github.com/FoundationDB/fdb-kubernetes-operator/blob/master/docs/cluster_spec.md#serviceconfig) the headless service option will create a service and select all Pods of this cluster the service is not used but Istio requires a Service to work correctly: https://istio.io/latest/docs/ops/deployment/requirements/#pod-requirements. This could solve your problem (maybe we need to add the according ports to the service.)

**Comment by johscheuer** [comment]
Hi @funkypenguin any news here? Did you have any success trying the changes?

**Comment by funkypenguin** [comment]
Hey @johscheuer - I had to back out of my Istio changes for now, and exclude the FDB pods from the mesh. I need to circle around and give it another try in the short-term, so I'll update you with the results soon :)

D

**Comment by funkypenguin** [comment]
Hey @johscheuer,

I'm sorry to report that the above suggestions have made no difference :(

What I've done:

1. Created a service which includes the operator:

```
root@cn1:~# kubectl describe service -n fdb-operator fdb-operator
Name:              fdb-operator
Namespace:         fdb-operator
Labels:            <none>
Annotations:       <none>
Selector:          app.kubernetes.io/instance=fdb-operator
Type:              ClusterIP
IP Families:       <none>
IP:                None
IPs:               None
Session Affinity:  None
Events:            <none>
root@cn1:~# kubectl get pods -n fdb-operator -l app.kubernetes.io/instance=fdb-operator
NAME                           READY   STATUS    RESTARTS   AGE
fdb-operator-bc9ff6546-7nlhw   2/2     Running   0          174m
root@cn1:~#
```

2. Ensured that all the fdb pods are configured as members of a headless service:

```
root@cn1:~# kubectl describe service -n preview-database-pr-162 retort-fdb
Name:              retort-fdb
Namespace:         preview-database-pr-162
Labels:            fdb-cluster-name=retort-fdb
Annotations:       <none>
Selector:          fdb-cluster-name=retort-fdb
Type:              ClusterIP
IP Families:       <none>
IP:                None
IPs:               None
Session Affinity:  None
Events:            <none>
root@cn1:~#
```

3. Upgraded to Istio 1.10.2 for good luck

Sadly, I still see the following in the istio-sidecar container on the operator, indicating that the traffic is destined for an IP, and therefore not traversing the mesh:

```
[2021-07-07T12:29:22.306Z] "- - -" 0 - - - "-" 112 0 11 - "-" "-" "-" "-" "10.117.88.107:8080" PassthroughCluster 10.117.88.64:54126 10.117.88.107:8080 10.117.88.64:54124 - -
[2021-07-07T12:29:22.248Z] "- - -" 0 UF,URX - - "-" 0 0 354 - "-" "-" "-" "-" "10.117.88.76:4501" PassthroughCluster - 10.117.88.76:4501 10.117.88.64:55854 - -
[2021-07-07T12:29:22.134Z] "- - -" 0 UF,URX - - "-" 0 0 1029 - "-" "-" "-" "-" "10.118.236.32:4501" PassthroughCluster - 10.118.236.32:4501 10.117.88.64:58406 - -
[2021-07-07T12:29:22.755Z] "- - -" 0 UF,URX - - "-" 0 0 966 - "-" "-" "-" "-" "10.117.88.76:4501" PassthroughCluster - 10.117.88.76:4501 10.117.88.64:55858 - -
```

The operator also logs:

```
{"level":"error","ts":1625660962.3194447,"logger":"controller","msg":"Error in reconciliation","namespace":"preview-database-pr-162","cluster":"retort-fdb","subReconciler":"controllers.GenerateInitialClusterFile","error":"GET http://10.117.88.107:8080/substitutions giving up after 11 attempt(s): Get \"http://10.117.88.107:8080/substitutions\": EOF","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/pkg/mod/github.com/go-logr/zapr@v0.2.0/zapr.go:132\ngithub.com/FoundationDB/fdb-kubernetes-operator/controllers.(*FoundationDBClusterReconciler).Reconcile\n\t/workspace/controllers/cluster_controller.go:176\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.3/pkg/internal/controller/controller.go:298\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.3/pkg/internal/controller/controller.go:253\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.3/pkg/internal/controller/controller.go:216\nk8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext.func1\n\t/go/pkg/mod/k8s.io/apimachinery@v0.20.4/pkg/util/wait/wait.go:185\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1\n\t/go/pkg/mod/k8s.io/apimachinery@v0.20.4/pkg/util/wait/wait.go:155\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil\n\t/go/pkg/mod/k8s.io/apimachinery@v0.20.4/pkg/util/wait/wait.go:156\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/go/pkg/mod/k8s.io/apimachinery@v0.20.4/pkg/util/wait/wait.go:133\nk8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext\n\t/go/pkg/mod/k8s.io/apimachinery@v0.20.4/pkg/util/wait/wait.go:185\nk8s.io/apimachinery/pkg/util/wait.UntilWithContext\n\t/go/pkg/mod/k8s.io/apimachinery@v0.20.4/pkg/util/wait/wait.go:99"}
{"level":"error","ts":1625660962.319647,"logger":"controller-runtime.manager.controller.foundationdbcluster","msg":"Reconciler error","reconciler group":"apps.foundationdb.org","reconciler kind":"FoundationDBCluster","name":"retort-fdb","namespace":"preview-database-pr-162","error":"GET http://10.117.88.107:8080/substitutions giving up after 11 attempt(s): Get \"http://10.117.88.107:8080/substitutions\": EOF","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/pkg/mod/github.com/go-logr/zapr@v0.2.0/zapr.go:132\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.3/pkg/internal/controller/controller.go:302\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.3/pkg/internal/controller/controller.go:253\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.3/pkg/internal/controller/controller.go:216\nk8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext.func1\n\t/go/pkg/mod/k8s.io/apimachinery@v0.20.4/pkg/util/wait/wait.go:185\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1\n\t/go/pkg/mod/k8s.io/apimachinery@v0.20.4/pkg/util/wait/wait.go:155\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil\n\t/go/pkg/mod/k8s.io/apimachinery@v0.20.4/pkg/util/wait/wait.go:156\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/go/pkg/mod/k8s.io/apimachinery@v0.20.4/pkg/util/wait/wait.go:133\nk8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext\n\t/go/pkg/mod/k8s.io/apimachinery@v0.20.4/pkg/util/wait/wait.go:185\nk8s.io/apimachinery/pkg/util/wait.UntilWithContext\n\t/go/pkg/mod/k8s.io/apimachinery@v0.20.4/pkg/util/wait/wait.go:99"}
```

So unless I can convince both the operator and the fdb pods themselves to talk to each other using DNS names, I think FDB won't play nicely with Istio :(

D

**Comment by johscheuer** [comment]
Ah right, the interception only works with DNS. For the operator this should be a trivial code change but I'm not aware of any plans for FoundationDB to move to DNS in the near future (at least for the whole cluster). You might ask that question in the https://forums.foundationdb.org/ or create an issue.

**Comment by funkypenguin** [comment]
Eureka! I've managed to make the operator, and fdb, work fully within Istio.

Although the following creates a headless service...

```
  services:
    headless: true
    publicIPSource: pod
```

... The resulting service it creates won't work for Istio, since it doesn't explicitly specify ports. I created a separate headless service, as follows:

```
apiVersion: v1
kind: Service
metadata:
  name: my-fdb-istio-compatible
spec:
  clusterIP: None
  selector:
    fdb-cluster-name: my-fdb
  type: ClusterIP
  ports:
  - port: 4500
    protocol: TCP
    targetPort: 4500
    name: tcp-fdb-tls       # needed for istio support    
  - port: 4501
    protocol: TCP
    targetPort: 4501
    name: tcp-fdb-non-tls   # needed for istio support    
  - port: 8080
    protocol: TCP
    targetPort: 8080
    name: tcp-fdb-operator  # needed for istio support
```

Of note here are that the service names are prefixed with `tcp-`, telling Istio not to bother inspecting SNI or host headers to work out the destination for the traffic, but just to send the traffic to the original destination.

I now have fdb-operator running in its own Istio mtls-enabled namespace, happily reconciling FDB CRs in multiple other namespaces, also mtls-enabled :)

**Comment by johscheuer** [comment]
Great news 🎉 Do you mind to write a short documentation on that? I think we can generate the headless service with these ports to remove the manual step. We also have the plan to expose some more flexibility in changing the created service but that's currently not a high priority.

**Comment by funkypenguin** [comment]
Sure, I'll write something up over the next day or two. I also intend to blog about it, since I consider it a significant personal achievement! :)

**Comment by johscheuer** [comment]
I'm going to close this issue as it seems you were able to setup everything.
