### ISSUE TITLE
Include backup and restore mechanism in the operator

### ISSUE THREAD

**Issue by viveksinghggits** [FoundationDB/fdb-kubernetes-operator#46]
If we install the foundationDB operator and create the cluster, in current implementation the backup and restore mechanisms dont get automatically enabled, especially backup_agent. Which makes the backup and restore of the foundationDB very difficult to achieve.

I thin we should have the backup_agent and other utilities, that enables us to take backup an restore, enabled in the default configuration or there should at least be a field in the FoundationDBCluster spec using which we can get those utilities enabled.

**Comment by brownleej** [comment]
I think there's a handful of tasks that we should take on to make it easy to manage backups through the operator:

[] Configuring backup agents
[] Starting, stopping, and pausing continuous backups
[] Restoring backups
[] Expiring old backup data
[] Deleting backups when a cluster is deleted

@viveksinghggits @JoshuaMcManus Can you think of anything else that we would need to handle for the backup lifecycle?

**Comment by viveksinghggits** [comment]
Hi @brownleej 
Just wanted to share that `backup_agent` binary is already present on the pods, ideally that should run as daemon but I dont think it runs as daemon as of now.

**Comment by brownleej** [comment]
I've created a label to track the overarching work, and issues for specific features of backup management.

**Comment by johscheuer** [comment]
@brownleej do you think it make sense to close this issue? We have this project to track the progress of the backup and restore work: https://github.com/FoundationDB/fdb-kubernetes-operator/projects/2
