### ISSUE TITLE
Add an option to use json logging

### ISSUE THREAD

**Issue by jkylling** [FoundationDB/fdb-kubernetes-operator#464]
Json logging is easier to parse and integrates better with cloud log viewers.

A flag could be added to toggle https://github.com/FoundationDB/fdb-kubernetes-operator/blob/bfc362ce084076de4ae5fe4d1fe7bb40c6665a56/main.go#L87 See, https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/log/zap/zap.go#L245

Alternatively, a flag could be added to set the zap-encoder.

**Comment by johscheuer** [comment]
I think a flag makes the most sense and it should be enabled per default since the operator will run in the most cases in a Kubernetes environment which uses some kind of a log forwarder to parse the logs and send them to a log sink.

**Comment by johscheuer** [comment]
Fixed by the mentioned PR.
