### ISSUE TITLE
The FDB plugin support FDB clusters that span across multiple Kubernetes clusters

### ISSUE THREAD

**Issue by johscheuer** [FoundationDB/fdb-kubernetes-operator#482]
The FDB operator allows to manage FDB clusters that are span across multiple Kubernetes clusters. The kubectl FDB plugin should also supports actions on such clusters. One way would be to specify multiple context(s) or to have some kind of configuration file that defines in which clusters a FDB cluster is available. This issue is mostly here to keep track of this feature before implementing it we probably want to come up with a design doc to see how we can implement it.

**Comment by brownleej** [comment]
This is a great idea! Maybe we could implement it as a kind of multi-KC apply operation, where we take a YAML for the cluster spec and apply it to all relevant KCs. We could infer some of that from the region configuration, and maybe add new fields to the spec that aren't used by the operator but can be used to specify where it needs to get deployed.

**Comment by brownleej** [comment]
We also have test scripts for creating multi-KC clusters that could be rewritten to use this feature in the plugin.

**Comment by johscheuer** [comment]
It probably makes sense to rework the current design of the `remove` command to be like `kubectl fdb create [type]` and `kubectl fdb delete [type]`  so it looks more like the normal kubectl commands. Adding an additional field would have the benefit that we don't need to create "yet another config file" and it would be more obvious where the FDB cluster is/should be running. I take a look at the multi dc/kc deployment and try to write down some implementable issues. One initial idea could be adding 2 new fields like `seed_kubernetes_cluster` and `kubernetes_clusters` (the latter one is just a list of additional Kubernetes contexts).

**Comment by johscheuer** [comment]
Closing since the design is merged and we have more specific issues for the implementation.
