### ISSUE TITLE
Add helm chart to deploy fdb operator 

### ISSUE THREAD

**Issue by PrasadG193** [FoundationDB/fdb-kubernetes-operator#49]

**Comment by brownleej** [comment]
This seems reasonable. I've heard this as an operator best practice before. I don't have much experience with Helm, though.

**Comment by viveksinghggits** [comment]
Hi @brownleej,
I have started working on having a helm chart to deploy the operator. We can use [github pages](https://helm.sh/docs/topics/chart_repository/#github-pages-example) to host that helm chart.
