### ISSUE TITLE
Automatic replacements if fault-domain is violated

### ISSUE THREAD

**Issue by johscheuer** [FoundationDB/fdb-kubernetes-operator#499]
In the automatic [replacement design doc](https://github.com/FoundationDB/fdb-kubernetes-operator/blob/master/docs/design/automatic_replacements.md) we initially focused on the replacement of Pod that are not running. I think we should extend this by also allowing the operator to replace Pods that violate our fault-domain. settings e.g. with the `affinityTerms` that we set and in the future the [topologySpreadConstraints](https://github.com/FoundationDB/fdb-kubernetes-operator/issues/361).

**Comment by brownleej** [comment]
Agreed, I think it makes sense to extend automatic replacements to automatic rebalancing across fault domains. I'm not sure if it will be necessary with topology spread constraints, since we may have stricter rules in that model, but we'll have to get deeper into that design to be sure.

**Comment by johscheuer** [comment]
I'm going to close this one. I believe in the current state this doesn't make too much sense, but once we implement the logical fault domain design https://github.com/FoundationDB/fdb-kubernetes-operator/blob/main/docs/design/bin_pack_fault_domains.md we have to implement it for this setup.
