### ISSUE TITLE
Missing a mechanism to configure clients in the same cluster

### ISSUE THREAD

**Issue by dougsparling** [FoundationDB/fdb-kubernetes-operator#53]
Hello! We've been experimenting with this operator, and getting an FDB cluster up and running was very smooth! However, when we then went to deploy some other services alongside it that connect to the new FDB cluster, it wasn't obvious how best to wire that up. In this case, our services are just some Go apps that use the Go FDB bindings and are expecting a cluster file.

Of course, I could copy+paste the cluster config into each service, but I was hoping for maybe some invocation of the sidecar that could drop a config into my services, or even a configmap containing the dynamic config. But I couldn't find anything.

I might be able to slice off some time to open a PR if this functionality is missing, depending on what you want it to look like!

**Comment by brownleej** [comment]
That's a great point. We have an open PR (#47) with some documentation on how to configure backup agents, and the configuration for those will be similar to what you need to get a client connected. We should also add an example with a client application connected. I've put in a request for an official sample app with a published docker image, which could help with that kind of example: https://github.com/apple/foundationdb/issues/2484

**Comment by dougsparling** [comment]
So it looks like I should be able to pull the cluster file out of the configmap created by the operator, right? In my case, it looks a little weird:

```Name:         fdb-config
...
Data
====
ca-file:
----

cluster-file:
----

fdbmonitor-conf-log:
----

fdbmonitor-conf-storage:
----

sidecar-conf:
----
{"ADDITIONAL_SUBSTITUTIONS":["FDB_INSTANCE_ID"],"COPY_BINARIES":["fdbserver","fdbcli"],"COPY_FILES":["fdb.cluster","ca.pem"],"COPY_LIBRARIES":[],"INPUT_MONITOR_CONF":"fdbmonitor.conf"}
Events:  <none>```

I tried mounting the configmap anyway to see if maybe there were clues about why they were empty, and it seemed like the files were broken symlinks?

```lrwxrwxrwx 1 root root   14 Dec 19 03:01 ca-file -> ..data/ca-file
lrwxrwxrwx 1 root root   19 Dec 19 03:01 cluster-file -> ..data/cluster-file
lrwxrwxrwx 1 root root   26 Dec 19 03:01 fdbmonitor-conf-log -> ..data/fdbmonitor-conf-log
lrwxrwxrwx 1 root root   30 Dec 19 03:01 fdbmonitor-conf-storage -> ..data/fdbmonitor-conf-storage
lrwxrwxrwx 1 root root   19 Dec 19 03:01 sidecar-conf -> ..data/sidecar-conf```

Perhaps when the operator went to build the configmap it copied symlinks instead of the files' contents? Sorry, I'm a tiny bit lost :)

**Comment by brownleej** [comment]
Have you confirmed that the operator has completed reconciliation? That looks like what the config map would be before it generated the initial cluster file, which happens after launching the first set of pods.

**Comment by dougsparling** [comment]
Not exactly, but it had been running for maybe 30 minutes, all pods were ready, and `fdbcli`'s status command reported ready, if that helps.

**Comment by brownleej** [comment]
yeah, that all suggests that reconciliation is complete. You can also determine this by describing the foundationdbcluster through kubectl. The status there will have information about which generation has been reconciled. If the pods are up, though, then the config map should be there too. Otherwise they wouldn't be able to get the monitor conf. You could try describing one of the pods and confirming which config map it's mounting, and making sure it's the same one you described above.

**Comment by dougsparling** [comment]
Oops, this one turned out to be my mistake. The reconciliation actually wasn't complete when I inspected the configmap. Once it finished, the cluster file was there. I had to do a bit more work after that to also mount the certificate in a place the client could find it, but everything worked!

Not sure if you want to close this one?

**Comment by brownleej** [comment]
We can keep it open to track the need for an example that shows how to do this with a client app.
