### ISSUE TITLE
Request to use `go mod` to manage the dependencies

### ISSUE THREAD

**Issue by viveksinghggits** [FoundationDB/fdb-kubernetes-operator#54]
We are using `go dep` to manage the dependencies for the operator but I think `go mod` is more mature and widely accepted dependency tool. We should start using `go mod` to manage the dependencies.

**Comment by brownleej** [comment]
Agreed! I tried this a while back and hit some problems with some of the dependencies, but I think those dependencies are gone now so it's worth another try.
