### ISSUE TITLE
Sidecar injector as WebHook

### ISSUE THREAD

**Issue by johscheuer** [FoundationDB/fdb-kubernetes-operator#549]
Currently the user always has to specify the FDB sidecar to inject libraries and and copy the cluster file. It might be useful if we had a WebHook that automatically injects the sidecar in the correct version so that a user only needs to annotate the `Deployment` with the required information and the FDB operator will inject the init container automatically.

**Comment by brownleej** [comment]
Is this for client deployments?

**Comment by johscheuer** [comment]
Yes, right. I just had the idea that this might be useful.

**Comment by johscheuer** [comment]
I don't think that this is an approach we want to follow.
