### ISSUE TITLE
Make it easier for operator clients to avoid the FDB C++ headers.

### ISSUE THREAD

**Issue by sears** [FoundationDB/fdb-kubernetes-operator#552]
We recently started using string constants from the package `"github.com/FoundationDB/fdb-kubernetes-operator/controllers"` which created a compile time dependency on the C++ FDB headers.  We'd rather not complicate our build environment by taking a direct dependency on the headers.  After discussing offline, we came up with two ideas:

- Client-facing constants (and related methods) could be consolidated in an API package
- Implementation code that requires the C++ client could be put in its own package to avoid polluting the rest of the logic with build-time dependencies.

Either approach seems reasonable to me.

**Comment by johscheuer** [comment]
I think both approaches make sense the first one has the benefit that all constants are in a common place and the latter one has the benefit that we can share public methods from the controller 👍

**Comment by johscheuer** [comment]
With the latest changed in the code only the usage of the `fdbclient` package should require the c++ headers. I'll close the issue. If there are still concerns/issue real free to reopen it.
