### ISSUE TITLE
Making sure that one stuck pod doesn't block other pods from getting config map updates

### ISSUE THREAD

**Issue by brownleej** [FoundationDB/fdb-kubernetes-operator#558]
When we are checking for updates to files from the config map, we stop as soon as we get an instance that has old configuration. The process for checking also calls APIs in the sidecar for copying files over, so if we have the ability to update an instance I think we're better off trying that as soon as we can, even if another instance is failing. I think we should try to make this more robust so we update every instance we can as soon as we can.

**Comment by johscheuer** [comment]
That should also speed up the reconciliation.
