### ISSUE TITLE
Remove unused endpoints in sidecar

### ISSUE THREAD

**Issue by johscheuer** [FoundationDB/fdb-kubernetes-operator#563]
The sidecar has currently some unused endpoints that we probably want to remove:

- `copy_binaries`
- `copy_libraries`
- `refresh_certs`
- `restart`

**Comment by brownleej** [comment]
I'm not sure if it makes sense to put this under the 1.0 milestone, since the sidecar is versioned independently of the operator.

**Comment by johscheuer** [comment]
I'll close this issue, with the efforts for the new sidecar image we are not investing that much time into the current sidecar.
