### ISSUE TITLE
Allowing multiple seed connection strings to get different DCs to reconcile

### ISSUE THREAD

**Issue by brownleej** [FoundationDB/fdb-kubernetes-operator#576]
When we run an FDB cluster across multiple data centers, we can get in a state where the operator instances in different Dcs have different configuration for what the cluster file is. It's important to be able to reliably get every operator instance to converge on the same cluster file. Given a list of potential candidates, an instance of the operator can choose the correct one, provided it can use at least one of them to talk to the database. We can provide a candidate through the seed connection string, but this is just a single value. If we have four potential candidates, we don't have a way of giving those to the operator. I think we would be better off allowing multiple seed connection strings. This would allow the following process for convergence:

1. Wait for every instance to reconcile.
2. Read the connection string from the status for each instance of the operator, and compile them into a set. If the set has a single entry, we are done. Otherwise, we go on to step 3.
3. Update each instance of the operator with the set from step 2. Return to step 1.

**Comment by johscheuer** [comment]
We are probably not working on this as we haven't seen any related issues since a while. If such an issues comes up again, we can reopen this issue.
