### ISSUE TITLE
Preventing operator from needing locks when pods are stuck in terminating

### ISSUE THREAD

**Issue by brownleej** [FoundationDB/fdb-kubernetes-operator#578]
When a pod is stuck in terminating, the operator will keep checking for the termination to complete. This currently involves taking a lock. This can cause problems with other instances of the operator that need a lock, because the operator with the stuck pod will keep extending the lock. I think that we should restrict the lock to cases where a resource needs to be deleted and is not already in terminating.

**Comment by johscheuer** [comment]
Fixed: https://github.com/FoundationDB/fdb-kubernetes-operator/pull/645
