### ISSUE TITLE
Sidecar should allow to copy all libraries

### ISSUE THREAD

**Issue by johscheuer** [FoundationDB/fdb-kubernetes-operator#600]
It could be useful to have a flag/option to just copy all current libraries to the targeted Pod instead of providing a list of the required versions.

**Comment by johscheuer** [comment]
@brownleej is this something we want to tackle in the current sidecar approach for only in the new one? I would prefer to move this specific implementation into the new one and leave the current implementation like it is.

**Comment by brownleej** [comment]
Yeah, I think unless there's an urgent need to modify the old sidecar we should focus our development efforts on the new image.
