### ISSUE TITLE
Using the sidecar to provide binaries to the operator instead of packaging all of them in the image

### ISSUE THREAD

**Issue by brownleej** [FoundationDB/fdb-kubernetes-operator#610]
We currently provide the FDB client binaries in the operator docker image. This means we have to update the operator image to support new versions of FoundationDB. I think this is a coupling that we should avoid. As an alternative, we should consider deploying the operator with the FDB sidecar image as an init container, so it can copy the binaries into a shared volume that the main image can use. We have an example of this pattern in our client examples.

**Comment by johscheuer** [comment]
The init container approach sounds reasonable to me.
