### ISSUE TITLE
Current 0.32 macOS kubectl fdb plugin is not a valid binary

### ISSUE THREAD

**Issue by mologie** [FoundationDB/fdb-kubernetes-operator#622]
Hello, I noticed that the recently released 0.32 kubectl-fdb binary cannot be run on macOS. It starts with a bunch of zeroes, so it's not a valid binary (no mach-o header).

Additionally the checksum file does not match what's downloaded. I have tried to download again with no change. Interestingly though the tar.gz file extracted just fine.

```
# hiccup @ reginn in ~/Downloads/kubectl-fdb-v0.32.0-macos [16:02:31] 
$ ./kubectl-fdb 
zsh: exec format error: ./kubectl-fdb

# hiccup @ reginn in ~/Downloads/kubectl-fdb-v0.32.0-macos [16:02:34] C:130
$ xxd kubectl-fdb | head -n10
00000000: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00000010: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00000020: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00000030: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00000040: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00000050: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00000060: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00000070: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00000080: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00000090: 0000 0000 0000 0000 0000 0000 0000 0000  ................

# hiccup @ reginn in ~/Downloads [16:05:40] 
$ cat kubectl-fdb-v0.32.0-macos.tar.gz.sha256 
31246b18fddcf92394328fa8a86234497c06d5974c0a19b584210015bad8ff2f

# hiccup @ reginn in ~/Downloads [16:06:16] 
$ sha256sum kubectl-fdb-v0.32.0-macos.tar.gz          
58e300521b84a01fb0d9afd8ebaa446e0d7bcdfbaabe4e778cd1e4a8ce0ec682  kubectl-fdb-v0.32.0-macos.tar.gz
```

My gut says a build machine of yours might have broken RAM (garbled binary during tar'ing, garbled sha256 input during checksumming).

**Comment by johscheuer** [comment]
Thanks for reporting! There might be a problem with the GitHub actions.

**Comment by johscheuer** [comment]
What version of MacOS are you running and do you use a M1?

**Comment by johscheuer** [comment]
Okay, so the sah256 issue is because GitHub actions calculate a "final" sha so I will create a PR to use `sah256` seems more reasonable to me and for the issue with the binary I will add an additional test that should catch that, could you try in the mean time the binary of the `v0.31.1` release this one works.

**Comment by mologie** [comment]
> What version of MacOS are you running and do you use a M1?

Latest stable (11.2.3), yes I am on M1 but Rosetta is available. Shouldn't be relevant though since the binary itself is broken according to `file`.

**Comment by johscheuer** [comment]
I rebuild the binaries for the release so you can also use them (the sha256 is still a different one until we merged my changes). You're welcome, thanks for reporting :)

**Comment by mologie** [comment]
Awesome, looks like everything is fine now. Thanks again!
