### ISSUE TITLE
Resource requests/limits have unexpected consequences

### ISSUE THREAD

**Issue by funkypenguin** [FoundationDB/fdb-kubernetes-operator#627]
Hey guys!

We've been increasing our use of our operator-managed FDB cluster, and we recently struggled with a period of instability, during which the clusters would "flap" between being unreachable and reachable.

After several days of debugging, we found that the fdb-server process (_we had a 512Mi limit_) was being OOMKilled by the kernel, but because it's a process spawned (_and subsequently restarted_) by fdb-monitor, the pod didn't terminate, and Kubernetes showed no issues.

The [official docs](https://apple.github.io/foundationdb/configuration.html#system-requirements) say that 4GB RAM is required, and there seems to be [some discussion](https://forums.foundationdb.org/t/foundationdb-ram-requirements/1646) around even 4GB being too small.

To this end, I'd like to make the following observations:

1. If I don't specify container resource limits in my clusterresource **at all**, I end up with 1GB RAM, 1vCPU. These limits may be too small, given the official requirements:

```
Containers:
  foundationdb:
    Image:      foundationdb/foundationdb:6.2.30
    Port:       <none>
    Host Port:  <none>
    Command:
      sh
      -c
    Args:
      fdbmonitor --conffile /var/dynamic-conf/fdbmonitor.conf --lockfile /var/dynamic-conf/fdbmonitor.lockfile --loggroup sample-cluster >> /var/log/fdb-trace-logs/fdbmonitor-$(date '+%Y-%m-%d').log 2>&1
    Limits:
      cpu:     1
      memory:  1Gi
    Requests:
      cpu:     1
      memory:  1Gi
```

2. If I specify resource **requests** but not **limits**, the limit are set to match my request, which is not what I wanted _(i.e., it's not possible to specify **no** limits)_ For example, this podTemplate:

```
      podTemplate:
        spec:
          containers:
            - name: foundationdb
              resources:
                requests:
                  cpu: 250m
                  memory: 128Mi
```

Results in these pod resource requests/limits:

```
  foundationdb:
    Container ID:  containerd://8b261228e5d76532da535f47c4e85158e8c83b88d022359afbabd993e3268136
    Image:         foundationdb/foundationdb:6.2.30
    Image ID:      docker.io/foundationdb/foundationdb@sha256:acc82cafb81fe42741f844cbcb1adf7501949c4b0ae523b7a63a22050232b92e
    Port:          <none>
    Host Port:     <none>
    Command:
      sh
      -c
    Args:
      fdbmonitor --conffile /var/dynamic-conf/fdbmonitor.conf --lockfile /var/dynamic-conf/fdbmonitor.lockfile --loggroup sample-cluster >> /var/log/fdb-trace-logs/fdbmonitor-$(date '+%Y-%m-%d').log 2>&1
    State:          Running
      Started:      Fri, 23 Apr 2021 02:58:23 +0000
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:     250m
      memory:  128Mi
    Requests:
      cpu:     250m
      memory:  128Mi
```

3. My final observation is that the fact that fdb-monitor restarts fdb-server, hides the OOMKill from standard monitoring / tooling. It's not even obvious from the log output that an OOMKill has occurred:

```
e="1619024070.823037" Severity="10" LogGroup="retort-fdb" Process="fdbserver.1": Launching /usr/bin/fdbserver (64) for fdbserver.1
Time="1619024072.695400" Severity="10" LogGroup="retort-fdb" Process="fdbserver.1": FDBD joined cluster.
Time="1619024174.036301" Severity="20" LogGroup="retort-fdb" Process="fdbserver.1": Process 64 terminated by signal 9, restarting in 0 second
s
```

May I suggest an option / configuration such that if a process in the pod dies, that the entire pod should die, so that Kubernetes can properly handle and report the failure?

Cheers!
D

**Comment by johscheuer** [comment]
I think 1. + 2. are just historical limitations that should be fixed (PRs are welcomed :)). For 3. This get's a little bit more interesting since we also restart the fdbserver process from the operator (e.g. for applying new fdbmonitor configuration or doing upgrades) we don't want the the Pod dies if the process get restarted. Probably the first step would be to add more visibility to this behaviour if you don't collect the trace-logs.

**Comment by brownleej** [comment]
It may also be desirable to have fdbmonitor treat voluntary restarts differently than exits due to failures. We could have it transparently restart processes that die with certain exit codes, but crash the container if the process exits due to failure. I don't think this would be desirable in all fdbmonitor configurations, but it might be desirable for the way we're using it on Kubernetes.

**Comment by brownleej** [comment]
I think the behavior of setting limits equal to requests is more likely to be what someone wants than the behavior of setting limits to the cluster-wide default. I believe you can accomplish the latter behavior by adding a limits section with the key `org.foundationdb/empty` set to `0`, but we should test and document that.
