### ISSUE TITLE
Rewrite sidecar in go

### ISSUE THREAD

**Issue by johscheuer** [FoundationDB/fdb-kubernetes-operator#630]
I think it makes sense to rewrite the current sidecar approach in Golang for a few reasons: 

- We don't need an interpreter runtime (and some additional tools) so our resulting image could be slimmer
- We can use the a template mechanism (go template) instead of using an search and replace mechanism
- We can use the same tooling to test our sidecar (currently untested) 
- Also I think it makes it simples to leverage the same code base in some places

**Comment by brownleej** [comment]
I agree. If we're going to move forward with the bigger set of changes discussed in #447, then that would also entail rewriting the sidecar in go, but with a different focus. I'll try to get that design into a state where we can do another round of review this week.

**Comment by johscheuer** [comment]
Closing, since the new unified sidecar is written in go
