### ISSUE TITLE
Remove the readinessProbe for the sidecar

### ISSUE THREAD

**Issue by johscheuer** [FoundationDB/fdb-kubernetes-operator#668]
In https://github.com/FoundationDB/fdb-kubernetes-operator/pull/666 we added support for a livenessProbe in the sidecar. before cutting the 1.0.0 release we want to remove the readinessProbe for the sidecar since we don't get any benefits of it (we always call directly the sidecar).

**Comment by brownleej** [comment]
I think the smoothest way to handle this transition is:
1. Introduce a new setting to enable the readiness probe, defaulting to true
2. In the next major release, default that to false and deprecate it
3. In the major release after that, remove the setting

This means we would need to go through two major releases to fully remove the code, but it means that there is no risk of a change to people's pod specs coming in a minor release.

**Comment by brownleej** [comment]
We've already introduced the new setting, which is all we can do in the 1.0 release.

**Comment by brownleej** [comment]
I think we can leave this as-is, until we have a broader sweep to remove support for the older sidecar model.
