### ISSUE TITLE
FDB analyze check for Node issues

### ISSUE THREAD

**Issue by johscheuer** [FoundationDB/fdb-kubernetes-operator#669]
We should add a flag to enable to check if any of the Nodes where a FDB Pod is running has some issues (e.g. is not ready) and if so printout the according Events.

**Comment by brownleej** [comment]
Nodes are a cluster-wide resource, so people managing FDB clusters may not have access to them if they're running in a shared Kubernetes environment. We may want a flag to skip node checks to support those kind of use cases.
