### ISSUE TITLE
Compare PodSpec should ignore default values

### ISSUE THREAD

**Issue by johscheuer** [FoundationDB/fdb-kubernetes-operator#677]
With the latest changes to the new CRD version (I would suspect we already had this issue before but we didn't noticed it) it can happen that Pods get updated because the `last-applied-spec-hash` due to changes how the default values are propagated (see: https://github.com/FoundationDB/fdb-kubernetes-operator/pull/676#issuecomment-837185719). In my opinion we should drop the spec hash comparison completely in https://github.com/FoundationDB/fdb-kubernetes-operator/blob/master/controllers/update_status.go#L561-L573 and just use [DeepDerivative](https://github.com/kubernetes/kubernetes/blob/2112bddae101b35934f1d66288449adf31243033/staging/src/k8s.io/apimachinery/third_party/forked/golang/reflect/deep_equal.go#L373-L377):

```go
if ! equality.Semantic.DeepDerivative(expected.Spec, current.Spec) {
   // ... incorrect spec
}
```

I think the comparison overhead shouldn't be to high (we have to test this with a benchmark) but the solutions should be better for defaults.

**Comment by brownleej** [comment]
We will need to check if there are cases where DeepDerivative misses a change, like removing a value that was previously set.

**Comment by johscheuer** [comment]
We might want to revisit this, the TLDR is that it's not that easy to get changes (especially if a field was deleted) between different specs.
