### ISSUE TITLE
Implement FoundationDBProcessGroup CRD

### ISSUE THREAD

**Issue by johscheuer** [FoundationDB/fdb-kubernetes-operator#687]
As part of the design in https://github.com/FoundationDB/fdb-kubernetes-operator/blob/master/docs/design/process_group_crd.md we want to add an additional intermediate CRD: `FoundationDBProcessGroup`. Part of this issue is to add the initial CRD and add some test cases for it without adding an additional controller.

**Comment by johscheuer** [comment]
Initially this CRD should be in the `v1alpha1` version.

**Comment by brownleej** [comment]
We're not actively prioritizing the FoundationDBProcessGroup project, so I don't think we need to leave this open.
