### ISSUE TITLE
Waiting to set HasPendingRemoval until the pod is in terminating

### ISSUE THREAD

**Issue by brownleej** [FoundationDB/fdb-kubernetes-operator#693]
We currently change the generation status from NeedsShrink to HasPendingRemoval/Reconciled as soon as the process is excluded. This can lead other tooling trying to move forward and analyze the pods, and get confused by the pods still being in a running state. I think we should only move the generation to HasPendingRemoval when all of the pods to be removed are both excluded (or skipping exclusion) and in a terminating state.

**Comment by johscheuer** [comment]
We should revisit that with the latest changes in the remove loop.

**Comment by brownleej** [comment]
This was fixed in #798
