### ISSUE TITLE
Provide a dev/CI Dockerfile to make contributions easier

### ISSUE THREAD

**Issue by Daniel-B-Smith** [FoundationDB/fdb-kubernetes-operator#703]
I have such a Dockerfile written up, but I'm creating an issue instead of a PR to facilitate discussion.

Currently, there is a large upfront cost to trying to contribute to the operator. Anything that changes the CRD requires a relatively large number of dependencies to be installed to even run the make commands to update the CRD. Running tests is an even larger hurdle. If the project had a dev/CI Dockerfile (or better yet a published Docker image similar to the dev image for FDB), contributors could simply use that container for development and not deal with the overhead of installing dependencies.  

In my ideal world, all CI would be run from this Docker image, and the release Dockerfile would use the CI Docker image as its builder stage. As things stand, there is already some skew in between CI and the release image.*

\* In particular, FDB 6.2.29 versus 6.2.30, and CI is likely using a version of go 1.15 newer than 1.15.8.

**Comment by johscheuer** [comment]
We made some changes to the FDB build image, so we can use the FDB build image (even thought it's huge) as the dev image.
