### ISSUE TITLE
Allow to use HTTP probe for sidecar

### ISSUE THREAD

**Issue by johscheuer** [FoundationDB/fdb-kubernetes-operator#704]
The next version (`6.3.13`) of the FoundationDB sidecar will contain a way to connect to the `/ready` without client cert authentication (https://github.com/FoundationDB/fdb-kubernetes-operator/pull/699) with that change we should also add a way to use a HTTP prob instead of a TCP probe for the sidecar.

**Comment by johscheuer** [comment]
@brownleej do you think we should tackle this before the 1.0 release? I think it would make sense to have the TCP probe for < `6.3.13` the default and otherwise use the http probe?

**Comment by brownleej** [comment]
I don't know. We don't want to make a latent change to pod specs, so we would need a setting in the spec to control the change to the new probe, and we want to avoid making any changes to the spec this close to the release.

**Comment by johscheuer** [comment]
Since we are moving away from the sidecar approach to the unified image we don't want to implement this feature.
