### ISSUE TITLE
Reducing repetition in the kustomize scripts for setting up the init containers for the operator

### ISSUE THREAD

**Issue by brownleej** [FoundationDB/fdb-kubernetes-operator#725]
In our kustomize config for the operator deployments, we have multiple init containers defined for copying binaries and libraries. This has a lot of repetition, since each container is using similar images, arguments, and volume mounts. We should look for ways to reduce this repetition.

**Comment by johscheuer** [comment]
I don't think that kustomize offers too much here since this would require some templating.

**Comment by johscheuer** [comment]
Closing, since kustomize doesn't offer a solution for that right now.
