### ISSUE TITLE
Drop support for 6.1

### ISSUE THREAD

**Issue by johscheuer** [FoundationDB/fdb-kubernetes-operator#743]
Given that the 6.1 release is now ~ 2years old with our any further releases/bug fixes (https://github.com/apple/foundationdb/tree/release-6.1) and 6.3 as the current (?) stable (?) version I would propose to drop the support for 6.1. Any concerns/vote against that?

I will cross post this in the forum and wait for the next release (2 weeks). If no concerns are raised I would vote for removal in the upcoming release (in 4 weeks for `v0.38.0`).

CC: @brownleej

**Comment by brownleej** [comment]
I think this would be a good thing to do as part of the 1.0 release of the operator.
