### ISSUE TITLE
Use resolver in process counts leads to an error

### ISSUE THREAD

**Issue by johscheuer** [FoundationDB/fdb-kubernetes-operator#745]
When configuring in the process counts the number of resolvers to a number bigger than 1 the cluster will never reconcile with the following error in the resolver Pod:

```bash
Time="1622886189.954714" Severity="10" LogGroup="test-cluster" Process="fdbserver.1": Launching /usr/bin/fdbserver (51) for fdbserver.1
Time="1622886189.957407" Severity="40" LogGroup="test-cluster" Process="fdbserver.1": ERROR: Unknown machine class `resolver'
Time="1622886189.957432" Severity="40" LogGroup="test-cluster" Process="fdbserver.1": Try `/usr/bin/fdbserver --help' for more information.
Time="1622886189.957832" Severity="40" LogGroup="test-cluster" Process="fdbserver.1": Process 51 exited 1, restarting in 56 seconds
```

and this is the `fdbmonitor.conf`:

```bash
at /var/dynamic-conf/fdbmonitor.conf
[general]
kill_on_configuration_change = false
restart_delay = 60
[fdbserver.1]
command = /usr/bin/fdbserver
cluster_file = /var/fdb/data/fdb.cluster
seed_cluster_file = /var/dynamic-conf/fdb.cluster
public_address = 10.1.12.121:4500:tls
class = resolver
logdir = /var/log/fdb-trace-logs
loggroup = test-cluster
datadir = /var/fdb/data
locality_instance_id = resolver-1
locality_machineid = test-cluster-resolver-1
locality_zoneid = test-cluster-resolver-1
```

and this is the process count spec:

```yaml
 processCounts:
    cluster_controller: 1
    proxy: 1
    resolver: 1
    stateless: -1
```

If I understand the code correctly it should be `resolution` instead of `resolver`: https://github.com/apple/foundationdb/blob/6.2.33/fdbrpc/Locality.cpp#L102-L118 

This would also match with the `fdbserver --help` output:

```bash
-c CLASS, --class CLASS
                 Machine class (valid options are storage, transaction,
                 resolution, proxy, master, test, unset, stateless, log, router,
                 and cluster_controller).
```

**Comment by brownleej** [comment]
We already have a `Resolution` field in the process counts, so I think we need to deprecate the `Resolver` count. While we're at it, we should review our ProcessCount fields to make sure they match this enum: https://github.com/apple/foundationdb/blob/6.3.14/fdbrpc/Locality.h#L27

**Comment by johscheuer** [comment]
Instead of deprecating we probably want to remove it even `6.1.*` doesn't have the `resolver` class: https://github.com/apple/foundationdb/blob/6.1.10/fdbrpc/Locality.h#L29 so this will be broken for all supported versions of FDB.

**Comment by brownleej** [comment]
I'm reluctant to remove fields from the spec outside of a major version update.

**Comment by johscheuer** [comment]
That's a fair point. I'll create a PR with the deprecation message and the warning that the setting doesn't work.
