### ISSUE TITLE
Provide up-to-date docker image

### ISSUE THREAD

**Issue by PierreZ** [FoundationDB/fdb-kubernetes-operator#75]
Hi!

I have started playing with this operator and was stuck on this error `quantities must match the regular expression '^([+-]?[0-9.]+)([eEinumkKMGTP]*[-+]?[0-9]*)$'`

```
 {"level":"error","ts":1578666059.9345756,"logger":"kubebuilder.controller","msg":"Reconciler error","controller":"foundationdbcluster-controller","request":"default/sample-cluster","error":"quantities must match the regular expression '^([+-]?[0-9.]+)([eEinumkKMGTP]*[-+]?[0-9]*)$'","stacktrace":"github.com/foundationdb/fdb-kubernetes-operator/vendor/github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/src/github.com/foundationdb/fdb-kubernetes-operator/vendor/github.com/go-logr/zapr/zapr.go:128\ngithub.com/foundationdb/fdb-kubernetes-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/src/github.com/foundationdb/fdb-kubernetes-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:217\ngithub.com/foundationdb/fdb-kubernetes-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1\n\t/go/src/github.com/foundationdb/fdb-kubernetes-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:158\ngithub.com/foundationdb/fdb-kubernetes-operator/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\t/go/src/github.com/foundationdb/fdb-kubernetes-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133\ngithub.com/foundationdb/fdb-kubernetes-operator/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/go/src/github.com/foundationdb/fdb-kubernetes-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134\ngithub.com/foundationdb/fdb-kubernetes-operator/vendor/k8s.io/apimachinery/pkg/util/wait.Until\n\t/go/src/github.com/foundationdb/fdb-kubernetes-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88"}
```

The error is happening when I'm using latest `sample-cluster.yml` with the current latest image on Docker Hub which is this one:

```
latest
Last updated 4 days ago by foundationdb
digest:sha256:78dd2d9ed5a34af2ffd2ef7c16a4a890ef6090d73dc477d8f79cfd3562c8c029
```

Pushing my own [Docker image](https://hub.docker.com/r/pierrezemb/fdb-kubernetes-operator/tags) based on latest commit did fix the issue.

Could you setup some CI to push images for each commits on Docker Hub?

Thanks.

**Comment by brownleej** [comment]
Sorry, I have a note to push an updated image based on something that was merged last night. I agree that we should set up CI to avoid this in the future.

**Comment by PierreZ** [comment]
No problem :wink:

**Comment by brownleej** [comment]
I've pushed a new image with the digest 2edff7968b4720f73c33adb8ce016247a4a107c0451e3aa52d0d03e21ff2b9cc. I've confirmed that I can create a cluster with this version of the operator using the sample in `config/samples/cluster_local.yaml`. Can you check if this resolves your issue?

**Comment by PierreZ** [comment]
Yes it does! Do you want to keep the issue open?

**Comment by brownleej** [comment]
I think we should keep this issue open to track the need to have the images built and published automatically, to prevent this from happening in the future.

**Comment by johscheuer** [comment]
Given the new [Docker Hub policies](https://www.docker.com/blog/scaling-docker-to-serve-millions-more-developers-network-egress) we might want to consider the GitHub Packages otherwise once we have a "tool user" for Docker Hub we it's probably straight forward to push a Docker Hub from master and tags (e.g. https://docs.github.com/en/free-pro-team@latest/actions/guides/publishing-docker-images)
