### ISSUE TITLE
Recovery after unexpected disruption to all nodes

### ISSUE THREAD

**Issue by funkypenguin** [FoundationDB/fdb-kubernetes-operator#750]
Hey guys!

We recently suffered an issue on one of our clusters which required us to reboot each node, without a managed `kubectl drain` first. Upon restart, each fdb pod had a new IP, and while all the data was presumably happily saved in the PVCs, the clusters wouldn't start up, and the operator wouldn't reconcile them.

I've duplicated the failure in a small dev cluster, by simply rebooting all the nodes at once. The pods eventually come back, but the FoundationDBCluster never reconciles. I anticipate that I could reproduce the problem by simply stopping the operator pod, and then deleting a few of the fdb pods, without the operator around to update the configmap.

Is there any way to mitigate the risk this poses in future?

Thanks!
D

**Comment by johscheuer** [comment]
That's a well known problem with the solution to use services in front of the Pods: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/283 and https://github.com/FoundationDB/fdb-kubernetes-operator/blob/master/docs/cluster_spec.md#serviceconfig

You should be able to revive your cluster by changing the connection string to use the new IPs.

**Comment by johscheuer** [comment]
I would close the issue since the documentation should be in place. If there is anything else feel free to reopen the issue or create a new one.
