### ISSUE TITLE
Restructure TLS settings and handling in the operator

### ISSUE THREAD

**Issue by johscheuer** [FoundationDB/fdb-kubernetes-operator#753]
Currently setting up a cluster with TLS enabled is rather "complex" and error prone with all the required settings e.g. see [TLS docs](https://github.com/FoundationDB/fdb-kubernetes-operator/blob/master/docs/manual/tls.md). Besides setting all fields correctly at the cluster Spec the user also has to set all required fields at the operator level with the limitation that the operator only can manage clusters with a shared CA. IMHO it's a good time to rethink how we want to handle TLS in the operator and how we can improve the user experience.

I would propose having a new `TLSConfig` setting that bundles all TLS related settings in one place currently they are distributed across multiple settings and trying to reduce the thinks a user has to provide e.g. it should be enough for the user to just provide the `secretName` and the operator could add all required env variables. I try to put a design doc together this week but I wanted to already create an issue for visibility and discussions.

**Comment by blindenvy** [comment]
Something to think about as well is it's often common for an operator and an operand to not exist in the same namespace. Often we find that operators are placed in a 'control plane' namespace and the operands in an 'instance' namespace. With that in mind managing this FDB operator is difficult because of the requirement on the operator needing the TLS certs which in most situations are pulled in from secrets. Secrets are namespace scoped. 

I also question how the operator functions like this when its managing multiple operands, is it expected that all operands use the same TLS certs?

It would be better if the operator did not need access to the TLS information for a particular instance to manage it.

**Comment by johscheuer** [comment]
I think we the restructuring of the TLS config it should be easier to implement a model where the TLS certs are dynamically fetched from Kubernetes instead of mounting them. That would allow the operator to consume secrets from other namespace (assuming RBAC is correctly setup) and dynamically use different secrets for clusters. I think both steps are in the end a follow up of changing the TLS config for clusters since in the current version of the cluster spec the operator wouldn't know where the secret is actually located, since it's mounted as a volume.

I also agree that these changes allow (human) operators  to use the fdb operator more flexible. 

> I also question how the operator functions like this when its managing multiple operands, is it expected that all operands use the same TLS certs?

Currently yes (at least they have to share the same CA and depending on the TLS validation on FDB side the client cert has to match the requirements).

> It would be better if the operator did not need access to the TLS information for a particular instance to manage it.

If the cluster is only listening on TLS the operator has to connect with the according certificates. The current way how that works, operator directly calls `fdbcli` or uses the golang bindings, we have to provide these certs. For the `fdbcli` case a workaround could be to exec into one Pod of the cluster to run these commands for the golang bindings that would be a little bit more complicated.

If you have any specific needs for that I'm happy to review any design docs or PR's related to that. For us this is currently not a high priority.

**Comment by brownleej** [comment]
This is pretty broad as it is, and I think if we have folks who are still interested we could move forward with more narrowly scoped issues.
