### ISSUE TITLE
Custom validation for TLS connections to the sidecar

### ISSUE THREAD

**Issue by brownleej** [FoundationDB/fdb-kubernetes-operator#756]
When we connect to the sidecar over TLS, it uses the default certificate validation rules, which require that the IP address is in the common name or alternative names for the certificate. This may not be appropriate for all certificate mechanisms, and is different from the kind of validation we use for FDB itself. We should look for ways to make this more flexible, possibly by supporting the same kind of validation options that FDB itself does.

**Comment by johscheuer** [comment]
With the `--tls-verify-peers` the sidecar already supports a subset of the FDB validation rules. Ist he concern that we don't support all validation rules from FDB (especially the special ones) or is the concern rather that we should change the way how the operator itself verifies the server certificate?

**Comment by brownleej** [comment]
Yes, I was thinking of the way the operator validates the server certificate. If we reïmplement the sidecar in go, that could reduce the duplication, but this would also all be mooted if we remove the connections between the operator and the sidecar, as you've suggested in previous discussions on rethinking the sidecar.

**Comment by johscheuer** [comment]
I would close this issue with the move to the new sidecar image we solved this issue by decoupling the communication and I don't think it's worth investing more time into the current approach.
