### ISSUE TITLE
New proxy configurations for FDB 7.0

### ISSUE THREAD

**Issue by brownleej** [FoundationDB/fdb-kubernetes-operator#757]
FDB 7.0 is introducing new configurations for proxies, where they are separated into commit_proxies and grv_proxies. We should add support for these configuration flags in the operator.

We will need to think about how to handle the transition. We currently set a default value for `proxies`, but we will probably want to transition to using the separate proxy settings as a default. Maybe we could introduce our own compatibility mode where we automatically translate `commit_proxies` and `grv_proxies` into a combined `proxies` count for older versions, and handle the different results from the status on 6.3 and 7.0.

**Comment by johscheuer** [comment]
@brownleej should we create a project to track the work for `7.0`?

**Comment by johscheuer** [comment]
Support was added in PR: https://github.com/FoundationDB/fdb-kubernetes-operator/pull/1114
