### ISSUE TITLE
Controlling what process classes can serve as coordinators

### ISSUE THREAD

**Issue by brownleej** [FoundationDB/fdb-kubernetes-operator#758]
We have some complex logic to preferentially select storage nodes as coordinators. This was put in place to make it easier to define pod disruption budgets that can specifically target coordinators. Rather than having this implicit preference, I think it would be better to allow people to specify what processes are eligible to be coordinators. This would allow people to restrict coordinators to storage nodes if their architecture sees advantages in it, with stronger guarantees because they can specify that they don't want to fall back to other process classes. It could also allow people to use a special coordinator process class which could allow them to use different storage options for them or otherwise customize the coordinator configuration.

**Comment by johscheuer** [comment]
Should we put a small design doc together for this one? I'm happy to help writing it down.

**Comment by johscheuer** [comment]
Thinking about this, we would also get the opportunity to limit the services created by the operator only to classes that are selected for coordinators.
