### ISSUE TITLE
PVC stuck in terminating is blocking reconciliation

### ISSUE THREAD

**Issue by brownleej** [FoundationDB/fdb-kubernetes-operator#764]
When we have a pod that is stuck in terminating, but the pod is fully excluded, we want to allow reconciliation to go forward. We have special logic in the RemovePods action that does this. However, if we have a PVC stuck in terminating, reconciliation gets blocked. Generally speaking if a pod is stuck in terminating, its associated PVC will be stuck in terminating too, so we need to account for this.

**Comment by johscheuer** [comment]
Same for Services. Good catch 👍
