### ISSUE TITLE
Implement FoundationDBProcessGroup controller

### ISSUE THREAD

**Issue by johscheuer** [FoundationDB/fdb-kubernetes-operator#767]
The initial implementation of the FoundationDBProcessGroup controller. The responsibility of the controller is to create/delete/update the underlying resources (Pods, PVCs, Services) and sync the state back to the `FoundationDBProcessGroup` CR e.g. `Pod created`, `Pod ready`. 

Design: https://github.com/FoundationDB/fdb-kubernetes-operator/blob/master/docs/design/process_group_crd.md

**Comment by brownleej** [comment]
We're not actively prioritizing the FoundationDBProcessGroup project, so we can close this until we're closer to acting on the design.
