### ISSUE TITLE
Multi FDB cluster support add fields in CRD

### ISSUE THREAD

**Issue by johscheuer** [FoundationDB/fdb-kubernetes-operator#771]
Part of this issue is to add the new fields `seedCluster` and `targetClusters` to the `FoundationDBCluster` CRD. The `FoundationDBCluster` should have a new method to get the resulting CRD for a specific `zoneID` or `dcID`. Otherwise no further actions should be added as part of this issue.

Design: https://github.com/FoundationDB/fdb-kubernetes-operator/blob/master/docs/design/plugin_multi_fdb_support.md

**Comment by brownleej** [comment]
We're not actively prioritizing this multi-cluster project, so we can close this until we're closer to acting on the design.
