### ISSUE TITLE
Multi FDB cluster support in plugin

### ISSUE THREAD

**Issue by johscheuer** [FoundationDB/fdb-kubernetes-operator#772]
Add generic support in the plugin to communicate with multiple Kubernetes clusters/contexts based on the `seedCluster` and `targetClusters` settings in a cluster CRD. I these fields are not set fall back to the "normal"/current mode. A simple command to support this should be the [version](https://github.com/FoundationDB/fdb-kubernetes-operator/blob/master/kubectl-fdb/cmd/version.go) command. The call of the version command should printout all operator versions in all clusters. We should support two modes (default) target all clusters or target a specific cluster. A potential third option would be target a subset of the cluster but I wouldn't implement this in the first step (as long as we don't see a need for that).

Design: https://github.com/FoundationDB/fdb-kubernetes-operator/blob/master/docs/design/plugin_multi_fdb_support.md

**Comment by brownleej** [comment]
We're not actively prioritizing this multi-cluster project, so we can close this until we're closer to acting on the design.
