### ISSUE TITLE
Multi FDB cluster support for analyze

### ISSUE THREAD

**Issue by johscheuer** [FoundationDB/fdb-kubernetes-operator#774]
Add support for the multi FDB cluster support in the `analyze` command.

Design: https://github.com/FoundationDB/fdb-kubernetes-operator/blob/master/docs/design/plugin_multi_fdb_support.md

**Comment by brownleej** [comment]
We're not actively prioritizing this multi-cluster project, so we can close this until we're closer to acting on the design.
