### ISSUE TITLE
Using time since last recovery to delay rolling bounces

### ISSUE THREAD

**Issue by brownleej** [FoundationDB/fdb-kubernetes-operator#804]
FDB 7.0 has a field called `seconds_since_last_recovered ` in the `recovery_state` for tracking how long it has been since the last recovery. I think we should integrate this into our rolling bounce, for versions where it is present, and require that the time between recoveries in a rolling bounce be at least 5 minutes.

**Comment by johscheuer** [comment]
Blocked by: https://github.com/apple/foundationdb/issues/8039
