### ISSUE TITLE
Changing the default external client directory

### ISSUE THREAD

**Issue by brownleej** [FoundationDB/fdb-kubernetes-operator#807]
We've introduced an option to use init containers to provide FDB binaries to the operator, and we are making use of that in our sample configurations. This requires setting a custom value for `FDB_NETWORK_OPTION_EXTERNAL_CLIENT_DIRECTORY` in the environment. I think we should make this the default.

This is a potentially breaking change, but it's pretty simple to implement, so we should do this as part of the next major release.

**Comment by johscheuer** [comment]
CC @09harsh that's a good candidate for you :)
