### ISSUE TITLE
Publishing documentation

### ISSUE THREAD

**Issue by brownleej** [FoundationDB/fdb-kubernetes-operator#832]
We have documentation for the operator in this repo, but it may not be the easiest experience to view and search it.  I think we should look into publishing it in a more readable form, possibly through GitHub pages.

**Comment by funkypenguin** [comment]
I stumbled across this issue by accident, and I'd like recommend to you [mkdocs](https://www.mkdocs.org/) with [material-for-mkdocs](https://squidfunk.github.io/mkdocs-material/)...

The advantage to mkdocs is that the documentation is readable in the repository as well as on the published documentation site (with search, navigation, etc).

For example, here's a documentation page on GitHub: https://github.com/geek-cookbook/geek-cookbook/blob/master/manuscript/recipes/funkwhale.md

And here's the corresponding published page: https://geek-cookbook.funkypenguin.co.nz/recipes/funkwhale/

Cheers!
D

**Comment by johscheuer** [comment]
I'm closing this one as we are probably busy with other things.
