### ISSUE TITLE
Configuring IPv6 for services

### ISSUE THREAD

**Issue by brownleej** [FoundationDB/fdb-kubernetes-operator#835]
As part of the broader work of supporting IPv6, we should ensure that users can configure services that are managed by the operator to use IPv6. This should include a smooth transition between IPv4 and IPv6.

**Comment by johscheuer** [comment]
Just linking the Kubernetes docs for reference: https://kubernetes.io/docs/concepts/services-networking/dual-stack/#services

**Comment by johscheuer** [comment]
Fixed in: https://github.com/FoundationDB/fdb-kubernetes-operator/pull/1754/
