### ISSUE TITLE
Supporting probes when customizing the pod IP family

### ISSUE THREAD

**Issue by brownleej** [FoundationDB/fdb-kubernetes-operator#836]
The operator has built-in readiness and licenses probes for the sidecar container. These probes use a TCP check, which will use the main pod IP. When we customize the pod IP family, the sidecar may not listen on the main pod IP, so these probes will not work. We should find a way to support these probes in conjunction with custom IP families.

**Comment by johscheuer** [comment]
Two things that come to my mind (and I'm not sure what's better/less horrible):

1. Use an exec probe with `curl` (or Python requests), that would also validate the certificate.
2. Always bind on `127.0.0.1` or `::1` in addition to the actual IP family.

**Comment by brownleej** [comment]
We should also keep an eye on the related issue in Kubernetes: https://github.com/kubernetes/kubernetes/issues/101324

**Comment by johscheuer** [comment]
Fixed in: https://github.com/FoundationDB/fdb-kubernetes-operator/pull/1754
