### ISSUE TITLE
Removing usage of Healthy flag in the database status

### ISSUE THREAD

**Issue by brownleej** [FoundationDB/fdb-kubernetes-operator#837]
We recently changed the database configuration subreconciler to check the replication health instead of the overall database health. The motivation behind this is that the overall health can go to unhealthy for a variety of reasons, some of which are not as serious and not relevant to what the action was trying to protect. I think we should look for other places where we are using the Healthy flag in the database status and look for more precise checks we can apply.

**Comment by johscheuer** [comment]
A quick scan over the code and I couldn't find any case where we use the health status of the database anymore. I think https://github.com/FoundationDB/fdb-kubernetes-operator/pull/908 removed the last occurrence where we used it. I'm going to close that isssue.
