### ISSUE TITLE
Debugging backup process & questions

### ISSUE THREAD

**Issue by vhadianto** [FoundationDB/fdb-kubernetes-operator#847]
Hello,

New to FoundationDB and trying to get it up and running. I've used the operator to successfully setup my FDB cluster and my app (in a separate container) connecting to it, but I'm struggling to get the backup running.

I'm trying to backup directly to Google Cloud Storage and have followed the example in the Operator Manual but I'm not entirely sure if I have the settings correct. Perhaps an expansion of the documentations is helpful here.

1. Is there a way to get the log from the backup agent to figure out what went wrong?
2. An example how to configure Google Cloud Storage will be helpful here. As for now I'm trying to guess what is the "account", "service", and "keys" are.
3. Also an example how to generate the self signed certificate will be very useful. As for the GCP config I'm guessing what the expected format are.

I'm more than happy to contribute the documentation for the above when I get this up and running.

Thanks!

**Comment by johscheuer** [comment]
Hi,

1. You can find the trace logs inside the foundationdb container under `/var/log/fdb-trace-logs`.
2. There are some discussions in the forum about using GCS as backup store: https://forums.foundationdb.org/t/how-do-i-use-fdbbackup-with-google-cloud-storage/1469 I think it's best to ask any specific GCS questions in the forum thread.

**Comment by vhadianto** [comment]
Hi @johscheuer 

Thanks, I think I'm a little further from getting this working in the k8s. There's a lot to digest in that log file (found them).

I am now first trying to get FDB blobstore backup working on a local installation first before trying to get this to work in a k8s cluster. I'll post question in the FDB forum as suggested and will open a new question here if there's something specific for the Operator.

**Comment by johscheuer** [comment]
Once you have everything running feel free to file a PR with some additional documentations steps for the setup. :)
