### ISSUE TITLE
FDB upgrades should allow to migrate transaction system

### ISSUE THREAD

**Issue by johscheuer** [FoundationDB/fdb-kubernetes-operator#856]
In the current implementation of upgrade we delete and recreate all Pods after the initial upgrade to ensure all Pods have the expected image. This has the drawback that this process will cause multiple recoveries if a Pod from the transaction system is deleted and recreated. Normally these recoveries shouldn't cause issues and the recovery should be very fast. One way to reduce the number of recoveries would be by migrating the transaction system that means once the cluster has done the initial upgrade we spin up a new transaction system or a batch (should be configurable) of new Pods and then exclude and delete the old once. This has the benefit that we only cause "number of batches" + 1 recoveries.

**Comment by brownleej** [comment]
I think there's now a few different places where we are configuring different scenarios where we do a migration vs a rolling bounce, and we should think about how to unify those in a way that makes it more discoverable and flexible.
