### ISSUE TITLE
Ignore Pods that are updated in bounce 

### ISSUE THREAD

**Issue by johscheuer** [FoundationDB/fdb-kubernetes-operator#869]
In the `getAddressesForUpgrade` method of the [bounce_processes](https://github.com/FoundationDB/fdb-kubernetes-operator/blob/master/controllers/bounce_processes.go#L210-L219) sub reconciler we can run in an issue if a user runs an FDB cluster spread across multiple Kubernetes Clusters or dc (any configuration that has multiple FDB cluster specs). If for some reason a cluster is already upgraded the method will block complaining that not all processes are added and these processes will never be added since from the point of view of the local operator the processes are upgraded and there is no need to add them to the `PendingUpgrades`. A simple solution to that would be to ignore processes that are already up-to-date e.g. by a replacement or some manual interaction. 

Like this:

```go
	for _, process := range databaseStatus.Cluster.Processes {
		processID := process.Locality["instance_id"]
		if process.Version == version.String() {
			continue
		}

		if pendingUpgrades[processID] {
			addresses = append(addresses, process.Address)
		} else {
			notReadyProcesses = append(notReadyProcesses, processID)
		}
	}
```

**Comment by AnnigeriShambu** [comment]
This is resolved in https://github.com/FoundationDB/fdb-kubernetes-operator/pull/884
