### ISSUE TITLE
Add additional fault tolerance check before deleting a ProcessGroup

### ISSUE THREAD

**Issue by johscheuer** [FoundationDB/fdb-kubernetes-operator#901]
We should define a setting that allows to user to define the threshold for fault tolerance when removing ProcessGroups e.g. as a user I should be able to define that the operator should only remove ProcessGroups when the fault tolerance is at the desired level or allow to remove ProcessGroups when the desired fault tolerance is `1`. Since FDB `6.3.13` we have detailed information for `storage`, `log` and `coordinator` fault tolerance, we should use these to allow the user to specify the appropriate surge they are comfortable with. In a follow up we could extend this setting to also allow to configure these settings based on the region for multi region clusters. I think https://github.com/FoundationDB/fdb-kubernetes-operator/blob/master/docs/cluster_spec.md#foundationdbclusterautomationoptions is the right place to put this configuration in. 

We could use a configuration like:

```yaml
excludeOptions:
    generalSurge: 1
    storageSurge: 1
    logSurge: 1
    coordinatorSurge: 1
```

This configuration would allow a different of 1 for each fault tolerance e.g. meaning we have one missing process where the data is not fully replicated. To reflect the current behaviour the default values would be `0`. The operator should always use the most specific value e.g. if `storageSurge` is set we will use that value if `storageSurge` is not set we will use `generalSurge` and if both are unset we will use `0` as default. As a note these surges will only be checked for stateful processes.

I'm open to a better naming/structure since this is only a proposal from my side.

**Comment by johscheuer** [comment]
@brownleej do you think we need a design doc got that?

**Comment by brownleej** [comment]
I think if we're going to make this highly customizable, and break it out by specific kinds of fault tolerance, it's worth putting it into a design doc.

**Comment by brownleej** [comment]
On the other hand, we could make this simpler by adding a hard rule that we don't delete any pods when fault tolerance is degraded in any way, and give users the fallback of manually deleting pods if this causes things to get stuck.

**Comment by johscheuer** [comment]
> ~On the other hand, we could make this simpler by adding a hard rule that we don't delete any pods when fault tolerance is degraded in any way, and give users the fallback of manually deleting pods if this causes things to get stuck.~
> 
> Crossing this out now that I see there's a PR for this exact thing :)

Thinking more about your comment I think you're right and we want to prevent some highly customisable setting that is probably hard to configure understand. So I would propose so have one setting to enable/disable fault tolerance checks (defaults to `true` but if for some kind of reasons the user decides to deactivate it that's fine). Internally the operator should be flexible enough to check the according fault tolerances:

- log processes will check the log fault tolerance 
- storage will check the storage fault tolerance
- coordinators will check the coordinator tolerance
- if these metrics are not available we use `fault_tolerance.max_zone_failures_without_losing_data`
- for the stateless processes we want to rely on `fault_tolerance.max_zone_failures_without_losing_availability`

I think heuristic here should be fairly simple to implement and good to be tested. As a last safety net we could require `full_replication`.

**Comment by johscheuer** [comment]
I think with the changes in our remove process group sub reconciler to check the fault tolerance and only delete process groups zone wise (per default) I think we did everything for this issue. Currently I don't see a need to have a more flexible way to define the fault tolerance checks.

I'm going to close this issue.
