### ISSUE TITLE
Allow to use more than one disk per Pod

### ISSUE THREAD

**Issue by johscheuer** [FoundationDB/fdb-kubernetes-operator#902]
The idea would be to allow the user to define something like `disksPerStoragePod` and the operator would create multiple PVC's for that Pod. The Pod would consume all these PVC's but still only run one `fdb` container (to keep the update logic simpler). This allows to run storage Pods with multiple disks, which could be useful for bin packing scenarios or where a user don't want to use/wast many IPs. This setting must also be working with the `storageServersPerDisk`. The default would be `1` and would reflect the current behaviour.

**Comment by brownleej** [comment]
We might also want to consider having more than just storage processes in the pod, allowing users to define a template for more complex pods that can effectively utilize entire nodes.

**Comment by johscheuer** [comment]
> We might also want to consider having more than just storage processes in the pod, ...

By Pod you actually mean container?

I see I was not really specific here, my unwritten assumption was:

- Every disk will have at leas 1 StorageServer (or `storageServersPerDisk`)

Some examples:

- `disksPerStoragePod` = 1 and `storageServersPerDisk` = 1, will result in 1 disk and 1 SS per disk per Pod, total SS per Pod will be 1
- `disksPerStoragePod` = 2 and `storageServersPerDisk` = 1, will result in 2 disks and 1 SS per disk per Pod, total SS per Pod will be 2
- `disksPerStoragePod` = 1 and `storageServersPerDisk` = 2, will result in 1 disk and 2 SS per disk per Pod, total SS per Pod will be 2
- `disksPerStoragePod` = 1 and `storageServersPerDisk` = 2, will result in 2 disk and 2 SS per disk per Pod, total SS per Pod will be 4

**Comment by brownleej** [comment]
I think that we would have all of the same processes in the same container, though that would also imply having all of the processes in the same pod 😄 

What about a layout like this, assuming the pod is called test-cluster-mega-pod-1:
* disk1: mega-pod-1-1 (storage), mega-pod-1-2 (storage)
* disk2: mega-pod-1-3 (storage), mega-pod-1-4 (storage)
* disk3: mega-pod-1-5 (storage), mega-pod-1-6 (storage)
* disk4: mega-pod-1-7 (transaction)
* no disk: mega-pod-1-8 (stateless), mega-pod-1-9 (stateless)

**Comment by johscheuer** [comment]
Oh, I see 😄 That would be probably another design. I think the first proposed idea with multiple disks for SS should be pretty simple the second proposal with one Pod as a logical container for multiple different FDB processes would be another design + additional complexity. I'm not sure if we want to go down this rabbit hole given the complexity in our code + configuration complexity. The benefits would be better bin packing (could be achieved with PodAffinitites) and reducing the required IPs per cluster. Are there any other benefits?

**Comment by brownleej** [comment]
Yeah, it's a tough trade-off. The benefits there (bin-packing and IP reduction) are the same category as the benefits in the original proposal, but they allow us to go even further.

**Comment by johscheuer** [comment]
@brownleej what are you thoughts on this (we can also discuss that offline). I would lean towards closing this issue as this will add additional complexity to the operator code and configuration and I'm not 100% sold on the benefits of this change. I believe it will be better to look again at: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/926 (I know those are not solving exactly the same issues but the goals is slightly overlapping).

**Comment by brownleej** [comment]
I'm fine with closing it.

**Comment by johscheuer** [comment]
If we discover the need for implementing such a design we can reopen this issue or create a new one.
