### ISSUE TITLE
Set GOMAXPROCS in operator deployment

### ISSUE THREAD

**Issue by johscheuer** [FoundationDB/fdb-kubernetes-operator#915]
We should set [GOMAXPROCS](https://pkg.go.dev/runtime#GOMAXPROCS) in our operator deployment to correctly define the maximum number of CPUs available for the operator.

**Comment by brownleej** [comment]
Do you think we can keep this in sync with the resource requests on the container through the downward API?

**Comment by johscheuer** [comment]
I'm not sure what happens when we have a value like `500m` I think the better way would be to use https://github.com/uber-go/automaxprocs

**Comment by johscheuer** [comment]
I think I spent sometime today adding this.
