### ISSUE TITLE
kubectl-plugin link is broken

### ISSUE THREAD

**Issue by xumengpanda** [FoundationDB/fdb-kubernetes-operator#935]
The link for  kubectl-fdb  at https://github.com/FoundationDB/fdb-kubernetes-operator/blob/master/docs/manual/debugging.md#kubectl-fdb-plugin is broken. 
Nothing happens when I clicked it.

It should point to https://github.com/FoundationDB/fdb-kubernetes-operator/blob/3cf8536df0eb536945ded4b18e8dfff64de20afa/kubectl-fdb/Readme.md?plain=1#L1

**Comment by johscheuer** [comment]
Thanks for reporting that issue. The anchor points to `/tree/master/kubectl-fdb` but actually it should be pointing to `/kubectl-fdb`.
