### ISSUE TITLE
How to run backups with --secure-connection=0?

### ISSUE THREAD

**Issue by funkypenguin** [FoundationDB/fdb-kubernetes-operator#961]
Hey guys!

I'm deliberately trying to avoid using a secure connection when doing backups, since I'm backing up to a Minio object store within my cluster, and the whole bang-shoot is already encrypted with mTLS.

I've managed to manually make a successful backup by execing into an FDB container, and appending `&sc=0` to my blobstore URL. How would I achieve this using the operator, since (at first glance) the operator runs `backup_agent`, which doesn't seem to include such an option?

My current hacky attempt (which may not even work) is simply to append `&sc=0` to the name of the bucket I define in the FoundationDBBackup resource :)

Cheers!
D

**Comment by johscheuer** [comment]
I'm going ahead and close this issue since the actual question was resolved. Feel free to create a PR with the arbitrary volumeMounts/ENV option and reopen the issue if there are any other questions.
