### ISSUE TITLE
Operator is not recreating the pod after removing it from buggify list

### ISSUE THREAD

**Issue by 09harsh** [FoundationDB/fdb-kubernetes-operator#979]
We have noticed that even after removing the pod from buggify list, the pod stays in the Pending state. As a workaround we are deleting the pod currently but we need to investigate and find a patch for it so that operator recreates the pod after it has been removed.

**Comment by johscheuer** [comment]
The important side note here is that the Pod is in a Pending state for longer than 5m which is our default detection time of a Pending Pod.

**Comment by brownleej** [comment]
Is this referring to the NoSchedule bug gift list?

**Comment by johscheuer** [comment]
Yes, the Pod was set into the `NoSchedule` state from the `buggify` list.

**Comment by johscheuer** [comment]
Was fixed in https://github.com/FoundationDB/fdb-kubernetes-operator/pull/1248
